# Generated by Django 6.0.1 on 2026-05-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportauditlog',
            new_name='portal_supp_branch__f33938_idx',
            old_name='portal_supp_branch__9a31d8_idx',
        ),
        migrations.RenameIndex(
            model_name='supportauditlog',
            new_name='portal_supp_actor_i_2437ab_idx',
            old_name='portal_supp_actor_i_0d4c2c_idx',
        ),
        migrations.RenameIndex(
            model_name='supportauditlog',
            new_name='portal_supp_action__536fa6_idx',
            old_name='portal_supp_action__bf983d_idx',
        ),
    ]
