# Generated by Django 6.0.1 on 2026-05-11 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_image'),
        ('portal', '0012_directorteacherassignment_planned_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('compact_mode', models.BooleanField(default=False)),
                ('default_section', models.CharField(choices=[('overview', 'Accueil'), ('classes', 'Mes classes'), ('supports', 'Supports'), ('schedule', 'Planning'), ('logs', 'Cahier de texte'), ('settings', 'Parametres')], db_index=True, default='overview', max_length=20)),
                ('notify_lesson_reminders', models.BooleanField(default=True)),
                ('notify_schedule_changes', models.BooleanField(default=True)),
                ('notify_support_messages', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_dashboard_preferences', to='branches.branch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_dashboard_preferences', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teacher_dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parametres dashboard enseignant',
                'verbose_name_plural': 'Parametres dashboard enseignants',
                'indexes': [models.Index(fields=['branch', 'teacher'], name='portal_teac_branch__a794cf_idx'), models.Index(fields=['teacher', 'default_section'], name='portal_teac_teacher_03f3ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'teacher'), name='portal_unique_teacher_dashboard_preference')],
            },
        ),
    ]
