# Generated by Django 6.0.5 on 2026-06-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_cash_reserve_target'),
        ('portal', '0015_alter_supportauditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('note_service', 'Note de service'), ('avis', 'Avis'), ('lettre', 'Lettre'), ('convocation', 'Convocation'), ('fiche_transfert', 'Fiche de transfert'), ('fiche_frequentation', 'Fiche de frequentation')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('recipients', models.TextField(blank=True, help_text='Destinataires (libre)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_documents', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document administratif',
                'verbose_name_plural': 'Documents administratifs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'doc_type'], name='portal_admi_branch__ce87c6_idx'), models.Index(fields=['branch', 'status'], name='portal_admi_branch__6a7649_idx')],
            },
        ),
    ]
