# Generated by Django 6.0.5 on 2026-07-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_ec_archived_at_ec_structure_status_ue_archived_at_and_more'),
        ('branches', '0003_branch_cash_reserve_target'),
        ('portal', '0016_administrativedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directorteacherassignment',
            name='portal_unique_director_teacher_assignment',
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='ends_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='scope_type',
            field=models.CharField(choices=[('class', 'Classe'), ('semester', 'Semestre'), ('ue', 'UE'), ('ec', 'EC')], db_index=True, default='class', max_length=20),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_teacher_assignments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='starts_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue'), ('archived', 'Archivee')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='suspended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_teacher_assignments', to='academics.ue'),
        ),
        migrations.AddField(
            model_name='directorteacherassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_director_teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='directorteacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'scope_type', 'academic_class', 'semester', 'ue', 'ec', 'starts_on', 'ends_on'), name='portal_unique_director_teacher_assignment'),
        ),
    ]
