# Generated by Django 6.0.5 on 2026-08-01 19:02

import django.db.models.deletion
import django.utils.timezone
import portal.models
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_existing_transfers(apps, schema_editor):
    TransferRequest = apps.get_model("portal", "TransferRequest")
    InternalTransfer = apps.get_model("portal", "InternalTransfer")
    OutgoingTransfer = apps.get_model("portal", "OutgoingTransfer")
    TransferSchool = apps.get_model("portal", "TransferSchool")

    for transfer in TransferRequest.objects.select_related("source_class", "target_class"):
        if transfer.reference is None:
            transfer.reference = uuid.uuid4()
        if transfer.submitted_at is None:
            transfer.submitted_at = transfer.created_at
        if transfer.transfer_type == "class":
            transfer.transfer_type = "internal"
            if transfer.target_class_id:
                InternalTransfer.objects.get_or_create(
                    transfer_request_id=transfer.pk,
                    defaults={
                        "target_programme_id": transfer.target_class.programme_id,
                        "target_class_id": transfer.target_class_id,
                        "source_level": transfer.source_class.level if transfer.source_class_id else transfer.target_class.level,
                        "target_level": transfer.target_class.level,
                    },
                )
        elif transfer.transfer_type == "school":
            transfer.transfer_type = "outgoing"
            school, _ = TransferSchool.objects.get_or_create(
                branch_id=transfer.branch_id,
                name=transfer.target_school_name or f"Établissement externe - dossier {transfer.pk}",
                city="",
            )
            OutgoingTransfer.objects.get_or_create(
                transfer_request_id=transfer.pk,
                defaults={"destination_school_id": school.pk},
            )
        if transfer.status == "validated":
            transfer.status = "completed"
            transfer.completed_at = transfer.reviewed_at or transfer.updated_at
        transfer.save(update_fields=[
            "reference", "submitted_at", "transfer_type", "status", "completed_at"
        ])


def reverse_transfer_normalization(apps, schema_editor):
    TransferRequest = apps.get_model("portal", "TransferRequest")
    TransferRequest.objects.filter(transfer_type="internal").update(transfer_type="class")
    TransferRequest.objects.filter(transfer_type="outgoing").update(transfer_type="school")
    TransferRequest.objects.filter(status="completed").update(status="validated")


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_remove_academiccalendarentry_supervisors'),
        ('admissions', '0004_candidature_completion_message_and_more'),
        ('branches', '0003_branch_cash_reserve_target'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
        ('portal', '0017_remove_directorteacherassignment_portal_unique_director_teacher_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='reference',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='academics.academicenrollment'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='source_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En étude'), ('awaiting_documents', 'Pièces à compléter'), ('approved', 'Approuvé'), ('handover', 'Remise en cours'), ('completed', 'Terminé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Transfert interne'), ('outgoing', 'Départ vers une autre école'), ('incoming', 'Arrivée depuis une autre école')], db_index=True, default='internal', max_length=20),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_level', models.CharField(max_length=20)),
                ('target_level', models.CharField(max_length=20)),
                ('academic_decision_reference', models.CharField(blank=True, max_length=120)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfer_placements', to='academics.academicclass')),
                ('target_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfer_destinations', to='formations.programme')),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_details', to='portal.transferrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Approuvé'), ('rejected', 'Rejeté')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_decisions', to=settings.AUTH_USER_MODEL)),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='portal.transferrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('request', 'Demande de transfert'), ('transcript', 'Relevé de notes'), ('clearance', 'Quitus administratif ou financier'), ('identity', "Pièce d'identité"), ('equivalence', "Décision d'équivalence"), ('other', 'Autre document')], default='request', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=portal.models.transfer_document_upload_path)),
                ('status', models.CharField(choices=[('pending', 'À vérifier'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.transferrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_transfer_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transfer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_partner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_schools', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfer_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'city'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_programme', models.CharField(blank=True, max_length=180)),
                ('destination_level', models.CharField(blank=True, max_length=40)),
                ('academic_check_completed', models.BooleanField(default=False)),
                ('administrative_check_completed', models.BooleanField(default=False)),
                ('financial_check_completed', models.BooleanField(default=False)),
                ('handover_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_details', to='portal.transferrequest')),
                ('destination_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_student_files', to='portal.transferschool')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('requested_level', models.CharField(max_length=20)),
                ('equivalence_notes', models.TextField(blank=True)),
                ('candidature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer', to='admissions.candidature')),
                ('requested_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_candidates', to='academics.academicclass')),
                ('requested_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='formations.programme')),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_details', to='portal.transferrequest')),
                ('origin_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_student_files', to='portal.transferschool')),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history_entries', to=settings.AUTH_USER_MODEL)),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portal.transferrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['transfer_request', 'created_at'], name='portal_tran_transfe_166780_idx')],
            },
        ),
        migrations.RunPython(normalize_existing_transfers, reverse_transfer_normalization),
        migrations.AlterField(
            model_name='transferrequest',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='transferschool',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'city'), name='portal_unique_transfer_school_branch_name_city'),
        ),
    ]
