# Generated by Django 6.0 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0018_transferrequest_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("note_service", "Note de service"),
                    ("avis", "Avis"),
                    ("lettre", "Lettre"),
                    ("convocation", "Convocation"),
                    ("fiche_transfert", "Fiche de transfert"),
                    ("fiche_frequentation", "Fiche de frequentation"),
                    ("attestation_preinscription", "Attestation de préinscription"),
                    ("lettre_mise_stage", "Lettre de mise en stage"),
                    ("presence_evaluation", "Fiche de présence à l'évaluation"),
                    ("pv_deliberation", "Procès-verbal de délibération"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
