# Generated by Django 6.0.5 on 2026-08-25 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_alter_evaluationcampaign_semester_number'),
        ('branches', '0003_branch_cash_reserve_target'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
        ('portal', '0019_alter_administrativedocument_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingtransfer',
            name='academic_reservations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='external_student_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='last_validated_semester',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='previous_academic_year',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='recognised_equivalences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='subjects_to_retake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='transferdocument',
            name='document_type',
            field=models.CharField(choices=[('request', 'Demande de transfert'), ('transcript', 'Relevé de notes'), ('school_certificate', 'Certificat de scolarité'), ('report_card', 'Bulletin'), ('level_certificate', 'Attestation de niveau'), ('diploma', 'Diplôme'), ('birth_certificate', 'Extrait de naissance'), ('study_programme', 'Programme académique suivi'), ('clearance', 'Quitus administratif ou financier'), ('identity', "Pièce d'identité"), ('equivalence', "Décision d'équivalence"), ('other', 'Autre document')], default='request', max_length=30),
        ),
        migrations.AlterField(
            model_name='transferdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'À vérifier'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('replace', 'À remplacer')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicEnrollmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('class_change', 'Changement de classe'), ('branch_transfer', 'Transfert inter-annexe'), ('programme_change', 'Changement de filière'), ('reclassification', 'Reclassement académique')], db_index=True, max_length=30)),
                ('effective_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source_level', models.CharField(max_length=40)),
                ('target_level', models.CharField(max_length=40)),
                ('reason', models.TextField()),
                ('observation', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_academic_movements', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements', to='academics.academicenrollment')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_academic_movements', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_from', to='branches.branch')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_from', to='academics.academicclass')),
                ('source_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_from', to='formations.programme')),
                ('target_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_to', to='branches.branch')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_to', to='academics.academicclass')),
                ('target_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_movements_to', to='formations.programme')),
                ('transfer_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_movement', to='portal.transferrequest')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['enrollment', 'effective_date'], name='portal_acad_enrollm_d04e5e_idx'), models.Index(fields=['source_branch', 'effective_date'], name='portal_acad_source__cab0ec_idx')],
            },
        ),
    ]
