# Generated by Django 6.0.5 on 2026-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentcorrection_financiallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiallog',
            name='action',
            field=models.CharField(choices=[('payment_created', 'Paiement cree'), ('payment_validated', 'Paiement valide'), ('payment_cancelled', 'Paiement annule'), ('payment_corrected', 'Paiement corrige'), ('expense', 'Depense'), ('export', 'Export'), ('print', 'Impression'), ('coupon_applied', 'Coupon applique')], db_index=True, max_length=40),
        ),
    ]
