# Generated by Django 6.0.1 on 2026-04-23 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_matricule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entry_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries_created', to=settings.AUTH_USER_MODEL)),
                ('related_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries_staff', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('submitted_by_name', models.CharField(max_length=255)),
                ('submitted_by_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='document_receipts/')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_receipts', to='students.student')),
                ('related_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='secretary.registryentry')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=50)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_tasks', to='students.student')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(db_index=True)),
                ('departed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], db_index=True, default='in_progress', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs_created', to=settings.AUTH_USER_MODEL)),
                ('related_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs_staff', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='students.student')),
            ],
            options={
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('related_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_related_staff', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='students.student')),
            ],
            options={
                'ordering': ['scheduled_at', 'title'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='secretary_a_status_94226e_idx'), models.Index(fields=['assigned_to', 'scheduled_at'], name='secretary_a_assigne_e7842d_idx'), models.Index(fields=['related_student', 'scheduled_at'], name='secretary_a_related_56fe81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['status', 'created_at'], name='secretary_r_status_a5d530_idx'),
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['related_student', 'status'], name='secretary_r_related_171fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['created_by', 'created_at'], name='secretary_r_created_356268_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreceipt',
            index=models.Index(fields=['status', 'received_at'], name='secretary_d_status_912528_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreceipt',
            index=models.Index(fields=['related_student', 'received_at'], name='secretary_d_related_20d8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreceipt',
            index=models.Index(fields=['related_registry', 'received_at'], name='secretary_d_related_c3e0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='secretarytask',
            index=models.Index(fields=['status', 'priority'], name='secretary_s_status_ab218a_idx'),
        ),
        migrations.AddIndex(
            model_name='secretarytask',
            index=models.Index(fields=['assigned_to', 'status'], name='secretary_s_assigne_8856a0_idx'),
        ),
        migrations.AddIndex(
            model_name='secretarytask',
            index=models.Index(fields=['related_student', 'status'], name='secretary_s_related_24df13_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['status', 'arrived_at'], name='secretary_v_status_8cf005_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['related_student', 'arrived_at'], name='secretary_v_related_57284c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['related_staff', 'arrived_at'], name='secretary_v_related_bb3370_idx'),
        ),
    ]
