# Generated by Django 6.0.5 on 2026-05-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_registry_metadata(apps, schema_editor):
    RegistryEntry = apps.get_model("secretary", "RegistryEntry")
    Profile = apps.get_model("accounts", "Profile")
    today = timezone.localdate()
    counters = {}
    for entry in RegistryEntry.objects.order_by("created_at", "id"):
        branch = entry.branch
        if branch is None and entry.created_by_id:
            profile = Profile.objects.filter(user_id=entry.created_by_id).select_related("branch").first()
            branch = getattr(profile, "branch", None)
        if branch is None and entry.related_student_id:
            candidature = getattr(getattr(entry.related_student, "inscription", None), "candidature", None)
            branch = getattr(candidature, "branch", None)

        branch_code = (getattr(branch, "code", "") or "GLOBAL").upper()
        created = entry.created_at or timezone.now()
        year = created.year
        key = (getattr(branch, "id", None), year)
        counters[key] = counters.get(key, 0) + 1
        daily_key = (getattr(branch, "id", None), created.date())
        counters[daily_key] = counters.get(daily_key, 0) + 1

        if not entry.registry_number:
            entry.registry_number = f"ESFE-{branch_code}-{year}-{counters[key]:06d}"
        if not entry.daily_number:
            entry.daily_number = counters[daily_key]
        if not entry.event_identifier:
            entry.event_identifier = f"{entry.registry_number}-{entry.daily_number:03d}"
        if branch is not None and not entry.branch_id:
            entry.branch = branch
        if not entry.priority:
            entry.priority = "normal"
        if not entry.target_service:
            entry.target_service = "Accueil"
        if not entry.workflow_code:
            entry.workflow_code = "administrative"
        if not entry.history:
            entry.history = [{"at": today.isoformat(), "by": "migration", "action": "backfill"}]
        entry.save(update_fields=[
            "registry_number",
            "daily_number",
            "event_identifier",
            "branch",
            "priority",
            "target_service",
            "workflow_code",
            "history",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_position_dga'),
        ('branches', '0002_branch_image'),
        ('secretary', '0001_initial'),
        ('students', '0011_studentyeardecision_decision_payload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registryentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='registry_attachments/'),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretary_registry_entries', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='daily_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='event_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='exited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='linked_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='motive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('immediate', 'Immediate')], db_index=True, default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='registry_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='student_class_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='target_service',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='visitor_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('transferred', 'Transfere'), ('completed', 'Traite'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('transferred', 'Transfere'), ('completed', 'Traite'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='entry_type',
            field=models.CharField(choices=[('parent_visit', 'Visite parent'), ('school_payment', 'Paiement scolarite'), ('package_deposit', 'Depot colis'), ('school_delivery', 'Livraison ecole'), ('appointment_request', 'Demande rendez-vous'), ('diploma_withdrawal', 'Retrait diplome'), ('complaint', 'Reclamation'), ('external_visitor', 'Visiteur externe')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('transferred', 'Transfere'), ('completed', 'Traite'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='secretarytask',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('transferred', 'Transfere'), ('completed', 'Traite'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('transferred', 'Transfere'), ('completed', 'Traite'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='in_progress', max_length=50),
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['branch', 'created_at'], name='secretary_r_branch__f6de6d_idx'),
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['entry_type', 'status'], name='secretary_r_entry_t_621ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='registryentry',
            index=models.Index(fields=['priority', 'status'], name='secretary_r_priorit_d74800_idx'),
        ),
        migrations.RunPython(backfill_registry_metadata, migrations.RunPython.noop),
    ]
