# Generated by Django 6.0.5 on 2026-07-13 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_cash_reserve_target'),
        ('secretary', '0002_registryentry_attachment_registryentry_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('internal', 'Réunion interne'), ('parent', 'Réunion parents'), ('external', 'Réunion externe'), ('emergency', "Réunion d'urgence")], db_index=True, default='internal', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='scheduled', max_length=30)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('agenda', models.TextField(blank=True, help_text='Ordre du jour')),
                ('participants', models.TextField(blank=True, help_text='Noms des participants, un par ligne')),
                ('secretary_present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Corps du procès-verbal')),
                ('decisions', models.TextField(blank=True, help_text='Décisions prises')),
                ('next_steps', models.TextField(blank=True, help_text='Actions à suivre')),
                ('redacted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='secretary.meeting')),
                ('redacted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_redacted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procès-verbal',
                'verbose_name_plural': 'Procès-verbaux',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['branch', 'scheduled_at'], name='secretary_m_branch__6a00b0_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='secretary_m_status_e5f04e_idx'),
        ),
    ]
