# Generated by Django 6.0.5 on 2026-08-25 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_cash_reserve_target'),
        ('secretary', '0003_meeting_and_minutes'),
        ('students', '0016_verification_log_staff_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('call_type', models.CharField(choices=[('incoming', 'Appel entrant'), ('outgoing', 'Appel sortant')], default='incoming', max_length=20)),
                ('interlocutor', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('target_service', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('immediate', 'Immediate')], default='normal', max_length=30)),
                ('call_status', models.CharField(choices=[('received', 'Reçu'), ('message_sent', 'Message transmis'), ('to_return', 'À rappeler'), ('returned', 'Rappel effectué'), ('processed', 'Traité')], db_index=True, default='received', max_length=30)),
                ('called_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_calls', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_calls_created', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_calls', to='students.student')),
            ],
            options={
                'ordering': ['-called_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'call_status', 'called_at'], name='secretary_s_branch__65c31d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecretaryTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('source_service', models.CharField(default='Secrétariat', max_length=120)),
                ('target_service', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('immediate', 'Immediate')], default='normal', max_length=30)),
                ('transmission_status', models.CharField(choices=[('sent', 'Transmis'), ('taken', 'Pris en charge'), ('processed', 'Traité'), ('closed', 'Clos')], db_index=True, default='sent', max_length=30)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_transmissions', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_transmissions_created', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_transmissions', to='students.student')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_transmissions_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'transmission_status', 'created_at'], name='secretary_s_branch__7c15bd_idx')],
            },
        ),
    ]
