# Generated by Django 6.0.1 on 2026-04-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_lessonlog'),
        ('branches', '0002_branch_image'),
        ('students', '0002_alter_student_options_alter_student_matricule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('absence_repetition', 'Absences repetitives'), ('late_repetition', 'Retards repetitifs')], db_index=True, max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alerts', to='branches.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'verbose_name': 'Alerte assiduite',
                'verbose_name_plural': 'Alertes assiduite',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['branch', 'triggered_at'], name='students_at_branch__c6d6c5_idx'), models.Index(fields=['student', 'alert_type'], name='students_at_student_553574_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'En retard')], db_index=True, max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendances', to='academics.academicclass')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendances', to='branches.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_student_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Presence etudiant',
                'verbose_name_plural': 'Presences etudiants',
                'ordering': ['-date', '-updated_at'],
                'indexes': [models.Index(fields=['academic_class', 'date'], name='students_st_academi_bca413_idx'), models.Index(fields=['branch', 'date'], name='students_st_branch__88b4e5_idx'), models.Index(fields=['status', 'date'], name='students_st_status_97c568_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='students_unique_attendance_student_date')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'En retard')], db_index=True, max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_attendances', to='branches.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_teacher_attendances', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presence enseignant',
                'verbose_name_plural': 'Presences enseignants',
                'ordering': ['-date', '-updated_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='students_te_branch__fe0f69_idx'), models.Index(fields=['teacher', 'date'], name='students_te_teacher_559640_idx'), models.Index(fields=['status', 'date'], name='students_te_status_a8f0e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date', 'branch'), name='students_unique_attendance_teacher_date_branch')],
            },
        ),
    ]
