# Generated by Django 6.0.1 on 2026-04-28 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_lessonlog'),
        ('branches', '0002_branch_image'),
        ('students', '0003_attendancealert_studentattendance_teacherattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='students_unique_attendance_student_date',
        ),
        migrations.RemoveConstraint(
            model_name='teacherattendance',
            name='students_unique_attendance_teacher_date_branch',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='schedule_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_attendances', to='academics.academicscheduleevent'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='schedule_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_attendances', to='academics.academicscheduleevent'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'schedule_event'), name='students_unique_attendance_student_schedule_event'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('teacher', 'schedule_event'), name='students_unique_attendance_teacher_schedule_event'),
        ),
    ]
