# Generated by Django 5.x

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0004_remove_studentattendance_students_unique_attendance_student_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRollSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "En cours"), ("validated", "Valide")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_roll_sheets",
                        to="academics.academicclass",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_roll_sheets",
                        to="branches.branch",
                    ),
                ),
                (
                    "schedule_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seance de reference pour la saisie groupee (optionnel).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_roll_sheets",
                        to="academics.academicscheduleevent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_attendance_roll_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_attendance_roll_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feuille d'appel (classe / jour)",
                "verbose_name_plural": "Feuilles d'appel (classe / jour)",
                "ordering": ["-date", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendancerollsheet",
            constraint=models.UniqueConstraint(
                fields=("branch", "academic_class", "date"), name="students_unique_roll_sheet_branch_class_date"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerollsheet",
            index=models.Index(fields=["branch", "date", "status"], name="students_at_branch_2f5f0d_idx"),
        ),
    ]
