# Generated by Django 6.0.1 on 2026-05-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendancerollsheet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerollsheet',
            new_name='students_at_branch__7fbe04_idx',
            old_name='students_at_branch_2f5f0d_idx',
        ),
    ]
