# Generated by Django 6.0.5 on 2026-05-07 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_image'),
        ('students', '0006_rename_students_at_branch_2f5f0d_idx_students_at_branch__7fbe04_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('absence_repetee', 'Absences répétées'), ('retard_frequent', 'Retards fréquents'), ('absence_longue', 'Absence longue'), ('signalement_comportemental', 'Signalement comportemental'), ('convocation_etudiant', 'Convocation étudiant'), ('convocation_parent', 'Convocation parent/tuteur'), ('suivi_pedagogique', 'Suivi pédagogique'), ('absent_evaluation', 'Absent à une évaluation'), ('enseignant_absent', 'Enseignant absent sur plusieurs cours'), ('signalements_multiples', 'Plusieurs signalements')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('attente_parent', 'En attente parent'), ('en_observation', 'En observation'), ('resolu', 'Résolu'), ('escalade', 'Escaladé direction')], db_index=True, default='nouveau', max_length=20)),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], db_index=True, default='normale', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_cases', to='branches.branch')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_student_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='students.student')),
            ],
            options={
                'verbose_name': 'Cas étudiant',
                'verbose_name_plural': 'Cas étudiants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.studentcase')),
            ],
            options={
                'verbose_name': 'Note de cas',
                'verbose_name_plural': 'Notes de cas',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentcase',
            index=models.Index(fields=['branch', 'status'], name='students_st_branch__e77bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcase',
            index=models.Index(fields=['student', 'status'], name='students_st_student_de426f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcase',
            index=models.Index(fields=['priority', 'status'], name='students_st_priorit_c25224_idx'),
        ),
    ]
