# Generated by Django 6.0.5 on 2026-05-17 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_current_academic_enrollment(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    AcademicEnrollment = apps.get_model("academics", "AcademicEnrollment")

    for student in Student.objects.filter(current_academic_enrollment__isnull=True).iterator():
        enrollment = (
            AcademicEnrollment.objects.filter(
                student_id=student.user_id,
                status="ACTIVE",
                is_active=True,
                is_archived=False,
            )
            .order_by("-created_at", "-id")
            .first()
        )
        if enrollment is None:
            enrollment = (
                AcademicEnrollment.objects.filter(student_id=student.user_id)
                .order_by("-created_at", "-id")
                .first()
            )
        if enrollment is not None:
            student.current_academic_enrollment_id = enrollment.id
            student.save(update_fields=["current_academic_enrollment"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_academicenrollment_status'),
        ('students', '0007_add_student_case_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_academic_enrollment',
            field=models.ForeignKey(blank=True, help_text="Inscription academique courante. L'ancien lien inscription reste conserve pour compatibilite.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academics.academicenrollment'),
        ),
        migrations.CreateModel(
            name='StudentYearDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('promoted', 'Passage'), ('repeated', 'Redoublement'), ('transferred', 'Transfert'), ('suspended', 'Suspension'), ('abandoned', 'Abandon'), ('completed', 'Cycle termine')], db_index=True, max_length=20)),
                ('annual_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_student_year_decisions', to=settings.AUTH_USER_MODEL)),
                ('source_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_year_decisions_as_source', to='academics.academicyear')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_year_decisions_as_source', to='academics.academicclass')),
                ('source_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_decisions', to='academics.academicenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_decisions', to='students.student')),
                ('target_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_year_decisions_as_target', to='academics.academicyear')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_year_decisions_as_target', to='academics.academicclass')),
            ],
            options={
                'verbose_name': 'Decision annuelle etudiant',
                'verbose_name_plural': 'Decisions annuelles etudiants',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_academic_year', 'decision'], name='students_st_source__129eb6_idx'), models.Index(fields=['source_class', 'decision'], name='students_st_source__856543_idx'), models.Index(fields=['target_academic_year', 'decision'], name='students_st_target__0686fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'source_enrollment'), name='students_unique_year_decision_per_enrollment')],
            },
        ),
        migrations.RunPython(backfill_current_academic_enrollment, migrations.RunPython.noop),
    ]
