# Generated by Django 6.0.5 on 2026-05-17 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_academicenrollment_status'),
        ('inscriptions', '0006_inscription_academic_class_and_more'),
        ('students', '0008_student_current_academic_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyeardecision',
            name='academic_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='academic_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_validated_student_year_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_student_year_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='finance_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='finance_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_validated_student_year_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='target_enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_year_decision', to='academics.academicenrollment'),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='target_inscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_year_decision', to='inscriptions.inscription'),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('academic_validated', 'Validee pedagogiquement'), ('finance_validated', 'Validee finance'), ('applied', 'Appliquee'), ('rejected', 'Rejetee')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='studentyeardecision',
            index=models.Index(fields=['workflow_status', 'created_at'], name='students_st_workflo_57e9a3_idx'),
        ),
    ]
