# Generated by Django 6.0.5 on 2026-05-17 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentyeardecision_academic_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyeardecision',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_student_year_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
