# Generated by Django 6.0.5 on 2026-05-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentyeardecision_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyeardecision',
            name='decision_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Trace de la regle academique automatique utilisee pour proposer la decision.'),
        ),
        migrations.AlterField(
            model_name='studentyeardecision',
            name='decision',
            field=models.CharField(choices=[('promoted', 'Passage'), ('promoted_with_debt', 'Passage avec dette'), ('repeated', 'Redoublement'), ('transferred', 'Transfert'), ('suspended', 'Suspension'), ('abandoned', 'Abandon'), ('completed', 'Cycle termine')], db_index=True, max_length=20),
        ),
    ]
