# Generated by Django 6.0.5 on 2026-06-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentyeardecision_decision_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('AB+', 'AB+'), ('AB-', 'AB−'), ('O+', 'O+'), ('O-', 'O−')], default='', help_text='Groupe sanguin déclaré (non vérifié médicalement)', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo d’identité pour la carte étudiant', upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='pin_hash',
            field=models.CharField(blank=True, default='', help_text='Code PIN haché pour l’authentification par carte', max_length=128),
        ),
        migrations.CreateModel(
            name='CarteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(help_text='Année académique, ex: 2026-2027', max_length=9)),
                ('code_annexe', models.CharField(help_text='Code annexe, ex: BKO-MORIBA', max_length=20)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('revoquee', 'Révoquée'), ('perdue', 'Perdue'), ('expiree', 'Expirée')], db_index=True, default='active', max_length=10)),
                ('token_version', models.CharField(default='v1', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='students.student')),
            ],
            options={
                'verbose_name': 'Carte étudiant',
                'verbose_name_plural': 'Cartes étudiants',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tente', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resultat', models.CharField(default='invalide', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='students.carteetudiant')),
            ],
            options={
                'verbose_name': 'Log de vérification carte',
                'verbose_name_plural': 'Logs de vérification carte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='carteetudiant',
            index=models.Index(fields=['etudiant', 'statut'], name='students_ca_etudian_887736_idx'),
        ),
        migrations.AddIndex(
            model_name='carteetudiant',
            index=models.Index(fields=['statut', 'date_expiration'], name='students_ca_statut_afce9e_idx'),
        ),
    ]
