# Generated by Django 6.0.5 on 2026-06-21 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_cash_reserve_target'),
        ('students', '0012_carte_etudiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcase',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('attente_parent', 'En attente parent'), ('en_observation', 'En observation'), ('convoque', 'Convoqué'), ('resolu', 'Résolu'), ('escalade', 'Escaladé direction')], db_index=True, default='nouveau', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('retard_repete', 'Retards répétés'), ('absence_non_justifiee', 'Absence non justifiée'), ('appel_non_fait', 'Appel non fait de façon récurrente'), ('manquement_pedagogique', 'Manquement pédagogique'), ('incident', 'Incident signalé'), ('autre', 'Autre')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('convoque', 'Convoqué'), ('resolu', 'Résolu')], db_index=True, default='nouveau', max_length=20)),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], db_index=True, default='normale', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_cases', to='branches.branch')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_teacher_cases', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cas enseignant',
                'verbose_name_plural': 'Cas enseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant')], db_index=True, max_length=10)),
                ('destinataire', models.CharField(blank=True, choices=[('etudiant', "L'étudiant"), ('parents', 'Les parents'), ('les_deux', 'Les deux')], max_length=10)),
                ('motif', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('call', 'Appel téléphonique'), ('email', 'E-mail'), ('letter', 'Courrier remis')], max_length=10)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('sent', 'Envoyée'), ('manual_pending', 'À traiter manuellement')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocations', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_convocations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='students.student')),
                ('student_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations', to='students.studentcase')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to=settings.AUTH_USER_MODEL)),
                ('teacher_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations', to='students.teachercase')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.teachercase')),
            ],
            options={
                'verbose_name': 'Note de cas enseignant',
                'verbose_name_plural': 'Notes de cas enseignant',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teachercase',
            index=models.Index(fields=['branch', 'status'], name='students_te_branch__67b889_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercase',
            index=models.Index(fields=['teacher', 'status'], name='students_te_teacher_60da4a_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercase',
            index=models.Index(fields=['priority', 'status'], name='students_te_priorit_fec516_idx'),
        ),
        migrations.AddConstraint(
            model_name='convocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('target_type', 'student'), ('teacher__isnull', True)), models.Q(('student__isnull', True), ('target_type', 'teacher'), ('teacher__isnull', False)), _connector='OR'), name='convocation_target_matches_fk'),
        ),
    ]
