# Generated by Django 6.0.1 on 2026-02-13 12:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('legal_status', models.CharField(blank=True, help_text='Statut juridique officiel', max_length=255)),
                ('approval_number', models.CharField(blank=True, help_text='Numéro d’agrément ou autorisation', max_length=255)),
                ('director_title', models.CharField(default='Direction Générale', max_length=255)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('hosting_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('legal', 'Mentions légales'), ('privacy', 'Politique de confidentialité'), ('terms', 'Conditions d’utilisation')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page légale',
                'verbose_name_plural': 'Pages légales',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='LegalPageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('content_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Historique de page',
                'verbose_name_plural': 'Historique des pages',
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Section légale',
                'verbose_name_plural': 'Sections légales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalSidebarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_blocks', to='core.legalpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
