# Generated by Django 6.0.1 on 2026-02-26 18:16

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Contenu principal du bloc.')),
                ('layout', models.CharField(choices=[('text_left', 'Texte gauche / Image droite'), ('text_right', 'Texte droite / Image gauche'), ('text_full', 'Texte pleine largeur'), ('gallery', 'Galerie d’images')], default='text_left', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image principale (non utilisée pour galerie).', null=True, upload_to='about/blocks/')),
                ('background_color', models.CharField(blank=True, help_text='Classe Tailwind optionnelle (ex: bg-gray-50)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloc À propos',
                'verbose_name_plural': 'Blocs À propos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement si laissé vide.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Courte description SEO optionnelle.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section À propos',
                'verbose_name_plural': 'Sections À propos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('legal_status', models.CharField(blank=True, help_text='Statut juridique officiel', max_length=255)),
                ('approval_number', models.CharField(blank=True, help_text='Numéro d’agrément ou autorisation', max_length=255)),
                ('director_title', models.CharField(default='Direction Générale', max_length=255)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('hosting_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='InstitutionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('legal', 'Mentions légales'), ('privacy', 'Politique de confidentialité'), ('terms', 'Conditions d’utilisation')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page légale',
                'verbose_name_plural': 'Pages légales',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='AboutBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Texte alternatif SEO.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aboutcontentblock')),
            ],
            options={
                'verbose_name': 'Image Bloc À propos',
                'verbose_name_plural': 'Images Bloc À propos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='aboutcontentblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.aboutsection'),
        ),
        migrations.CreateModel(
            name='LegalPageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('content_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Historique de page',
                'verbose_name_plural': 'Historique des pages',
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Section légale',
                'verbose_name_plural': 'Sections légales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalSidebarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_blocks', to='core.legalpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(choices=[('admission', 'Admission'), ('formation', 'Information formation'), ('inscription', 'Inscription administrative'), ('payment', 'Paiement'), ('partnership', 'Partenariat'), ('complaint', 'Réclamation'), ('other', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, help_text='Réponse envoyée au contact')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('sla_hours', models.PositiveIntegerField(default=48, help_text='Temps maximal de traitement en heures')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('answered', 'Répondu'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_contac_status_de41ec_idx'), models.Index(fields=['priority'], name='core_contac_priorit_5f9b6e_idx'), models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx')],
            },
        ),
    ]
