# Generated by Django 6.0.1 on 2026-02-27 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institution_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionstat',
            options={'ordering': ['order'], 'verbose_name': 'Statistique', 'verbose_name_plural': 'Statistiques'},
        ),
        migrations.AlterModelOptions(
            name='legalsidebarblock',
            options={'ordering': ['order'], 'verbose_name': 'Bloc sidebar légal', 'verbose_name_plural': 'Blocs sidebar légaux'},
        ),
        migrations.AddField(
            model_name='institutionstat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legalsidebarblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutblockimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutcontentblock',
            name='background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutcontentblock',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutcontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/blocks/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='institution',
            name='approval_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='legal_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
