# Generated by Django 6.0.1 on 2026-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, help_text='Réponse envoyée au contact'),
        ),
    ]
