# Generated by Django 6.0.1 on 2026-02-28 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_institutionstat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontentblock',
            name='section',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='slug',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='background',
            field=models.CharField(default='white', help_text='white | light | primary', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='highlights',
            field=models.JSONField(blank=True, help_text="Liste des points clés (ex: ['Reconnu par l’État', 'Système LMD'])", null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe icône (ex: fa-solid fa-graduation-cap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_key',
            field=models.CharField(blank=True, choices=[('identity', 'Identité de l’école'), ('vision', 'Vision & Mission'), ('governance', 'Gouvernance'), ('infrastructure', 'Infrastructures'), ('student_life', 'Vie étudiante'), ('network', 'Annexes & Partenariats')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AboutBlockImage',
        ),
        migrations.DeleteModel(
            name='AboutContentBlock',
        ),
    ]
