# Generated by Django 6.0.1 on 2026-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_infrastructure_institutionpresentation_staff_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/branding/', verbose_name='Logo principal')),
                ('home_hero_image', models.ImageField(blank=True, null=True, upload_to='site/home/hero/', verbose_name='Image Hero Accueil')),
                ('home_hero_title', models.CharField(default='ESFE', max_length=255, verbose_name='Titre Hero Accueil')),
                ('home_hero_subtitle', models.CharField(default='Former les cadres de la santé', max_length=500, verbose_name='Sous-titre Hero Accueil')),
                ('home_about_image', models.ImageField(blank=True, null=True, upload_to='site/home/about/')),
                ('home_why_image_1', models.ImageField(blank=True, null=True, upload_to='site/home/why/')),
                ('home_why_image_2', models.ImageField(blank=True, null=True, upload_to='site/home/why/')),
                ('home_why_image_3', models.ImageField(blank=True, null=True, upload_to='site/home/why/')),
                ('home_why_image_4', models.ImageField(blank=True, null=True, upload_to='site/home/why/')),
                ('home_annexe_image_1', models.ImageField(blank=True, null=True, upload_to='site/home/annexes/')),
                ('home_annexe_image_2', models.ImageField(blank=True, null=True, upload_to='site/home/annexes/')),
                ('home_annexe_image_3', models.ImageField(blank=True, null=True, upload_to='site/home/annexes/')),
                ('home_annexe_image_4', models.ImageField(blank=True, null=True, upload_to='site/home/annexes/')),
                ('home_stats_banner_image', models.ImageField(blank=True, null=True, upload_to='site/home/banners/', verbose_name='Banniere statistiques Accueil')),
                ('about_hero_image', models.ImageField(blank=True, null=True, upload_to='site/about/hero/')),
                ('about_main_image', models.ImageField(blank=True, null=True, upload_to='site/about/main/')),
                ('about_stats_banner_image', models.ImageField(blank=True, null=True, upload_to='site/about/banners/')),
                ('about_vision_title', models.CharField(default='Notre Vision', max_length=255)),
                ('about_vision_text', models.TextField(blank=True)),
                ('about_values_title', models.CharField(default='Nos Valeurs', max_length=255)),
                ('about_values_subtitle', models.CharField(blank=True, max_length=500)),
                ('smart_rocket_enabled', models.BooleanField(default=True)),
                ('smart_rocket_title', models.CharField(default='Assistant ESFE', max_length=120)),
                ('smart_rocket_message', models.CharField(default='Accedez rapidement aux actions clés.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('candidature_submitted', 'Candidature soumise'), ('candidature_under_review', "Candidature en cours d'analyse"), ('candidature_to_complete', 'Candidature à compléter'), ('candidature_accepted', 'Candidature acceptée'), ('candidature_accepted_with_reserve', 'Candidature acceptée sous réserve'), ('candidature_rejected', 'Candidature refusée'), ('inscription_created', 'Inscription créée'), ('inscription_payment_pending', 'Inscription en attente de paiement'), ('inscription_partial_payment', 'Inscription avec paiement partiel'), ('inscription_active', 'Inscription active'), ('inscription_suspended', 'Inscription suspendue'), ('inscription_expired', 'Inscription expirée'), ('inscription_completed', 'Inscription terminée'), ('payment_received', 'Paiement reçu'), ('payment_validated', 'Paiement validé'), ('document_missing', 'Document manquant')], max_length=50),
        ),
    ]
