# Generated by Django 6.0.1 on 2026-02-23 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='Temps maximal de traitement en heures'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status'], name='core_contac_status_de41ec_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority'], name='core_contac_priorit_5f9b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx'),
        ),
    ]
