# Generated by Django 6.0.1 on 2026-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/hero/', verbose_name='Image Hero (A propos)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/main/', verbose_name='Image principale de presentation (A propos)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='home_about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/home/about/', verbose_name='Image section Qui sommes-nous (Accueil)'),
        ),
    ]
