# Generated by Django 6.0.1 on 2026-02-14 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_rename_admissions_status_idx_admissions__status_c3c8ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_token', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('access_code', models.CharField(blank=True, help_text='Code d’accès privé au dossier', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Créée'), ('active', 'Active'), ('suspended', 'Suspendue')], default='created', max_length=20)),
                ('amount_due', models.PositiveIntegerField(help_text='Montant total à payer pour cette inscription (FCFA)')),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='Montant déjà payé (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inscription', to='admissions.candidature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
