# Generated by Django 6.0.1 on 2026-05-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_language_profession'),
        ('inscriptions', '0005_alter_statushistory_options_inscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academics.academicclass'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='academic_level',
            field=models.CharField(blank=True, help_text='Niveau academique positionne administrativement.', max_length=10),
        ),
    ]
