# Generated by Django 6.0.5 on 2026-07-03 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_branch_cash_reserve_target'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
        ('inscriptions', '0006_inscription_academic_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code communiqué au candidat (ex: MASTER-DG-2026).', max_length=32, unique=True)),
                ('label', models.CharField(help_text="Description interne (ex: 'Réduction DG - promo rentrée 2026').", max_length=150)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed_amount', 'Montant fixe (FCFA)')], max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Pourcentage (1-100) si type=Pourcentage, sinon montant en FCFA.')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations au total. Vide = illimité.", null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Annexes concernées. Laisser vide = applicable à toutes les annexes.', related_name='coupons', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
                ('programmes', models.ManyToManyField(blank=True, help_text='Formations concernées. Laisser vide = applicable à toutes les formations.', related_name='coupons', to='formations.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_before', models.PositiveBigIntegerField()),
                ('amount_after', models.PositiveBigIntegerField()),
                ('discount_amount', models.PositiveBigIntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupons.coupon')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemption', to='inscriptions.inscription')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_cou_is_acti_a50634_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='coupons_cou_valid_f_ac5256_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'applied_at'], name='coupons_cou_coupon__fe4c94_idx'),
        ),
    ]
