# Generated by Django 6.0.5 on 2026-05-26 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0019_academicbulletin_academicdiplomaaward'),
        ('branches', '0002_branch_image'),
        ('formations', '0008_delete_programavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('brevo_api_key_label', models.CharField(blank=True, max_length=120)),
                ('popup_primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('popup_duration_seconds', models.PositiveSmallIntegerField(default=8)),
                ('notification_behaviour', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametre marketing',
                'verbose_name_plural': 'Parametres marketing',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_scope', models.CharField(choices=[('all', 'Tout ESFE'), ('branches', 'Annexes selectionnees'), ('custom', 'Ciblage avance')], db_index=True, default='all', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('audience_tags', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('announcement_type', models.CharField(choices=[('event', 'Evenement'), ('general', 'Annonce generale'), ('urgency', 'Urgence'), ('reminder', 'Rappel'), ('academic', 'Information academique'), ('dg', 'Communication DG'), ('course_suspension', 'Suspension cours'), ('internal_campaign', 'Campagne interne')], db_index=True, default='general', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiee'), ('active', 'Active'), ('expired', 'Expiree'), ('archived', 'Archivee')], db_index=True, default='draft', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('show_popup', models.BooleanField(db_index=True, default=False)),
                ('is_blocking_popup', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_announcements', to=settings.AUTH_USER_MODEL)),
                ('branches', models.ManyToManyField(blank=True, to='branches.branch')),
                ('classes', models.ManyToManyField(blank=True, to='academics.academicclass')),
                ('cycles', models.ManyToManyField(blank=True, to='formations.cycle')),
                ('formations', models.ManyToManyField(blank=True, to='formations.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_scope', models.CharField(choices=[('all', 'Tout ESFE'), ('branches', 'Annexes selectionnees'), ('custom', 'Ciblage avance')], db_index=True, default='all', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('audience_tags', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('objective', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiee'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminee'), ('archived', 'Archivee')], db_index=True, default='draft', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email Brevo'), ('whatsapp_future', 'WhatsApp futur'), ('sms_future', 'SMS futur')], db_index=True, default='email', max_length=30)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('budget_estimate', models.PositiveBigIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('brevo_campaign_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, to='branches.branch')),
                ('classes', models.ManyToManyField(blank=True, to='academics.academicclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
                ('cycles', models.ManyToManyField(blank=True, to='formations.cycle')),
                ('formations', models.ManyToManyField(blank=True, to='formations.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('estimated_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_segments', to='marketing.campaign')),
            ],
            options={
                'ordering': ['campaign', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=40)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoye'), ('failed', 'Erreur'), ('skipped', 'Ignore')], db_index=True, default='pending', max_length=20)),
                ('audience_snapshot', models.JSONField(blank=True, default=dict)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='marketing.announcement')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='marketing.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_dispatch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('media_type', models.CharField(choices=[('poster', 'Affiche'), ('video', 'Video'), ('logo', 'Logo'), ('pdf', 'PDF'), ('reel', 'Reel'), ('flyer', 'Flyer'), ('jingle', 'Jingle')], db_index=True, default='poster', max_length=20)),
                ('file', models.FileField(upload_to='marketing/media/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='marketing_media', to='branches.branch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=160)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('website', 'Site web'), ('form', 'Formulaire'), ('newsletter', 'Newsletter'), ('csv', 'Import CSV'), ('event', 'Evenement'), ('campaign', 'Campagne')], db_index=True, default='form', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('consent_email', models.BooleanField(default=True)),
                ('brevo_contact_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_prospects', to='branches.branch')),
                ('interested_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_prospects', to='formations.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('recurrence', models.CharField(blank=True, max_length=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='marketing.campaign')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'priority', 'starts_at'], name='marketing_a_status_118a73_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type', 'status'], name='marketing_a_announc_045e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'channel', 'starts_at'], name='marketing_c_status_f47ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='marketing_d_channel_9b9ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingmedia',
            index=models.Index(fields=['media_type', 'is_archived'], name='marketing_m_media_t_ef3079_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectlead',
            index=models.Index(fields=['source', 'created_at'], name='marketing_p_source_7e2cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledcampaign',
            index=models.Index(fields=['is_processed', 'scheduled_for'], name='marketing_s_is_proc_47e7fd_idx'),
        ),
    ]
