# Generated by Django 6.0.1 on 2026-02-14 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidature',
            new_name='admissions__status_c3c8ed_idx',
            old_name='admissions_status_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='admissions__program_87ac59_idx',
            old_name='admissions_programme_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='admissions__program_4d353e_idx',
            old_name='admissions_prog_year_status_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='admissions__academi_459930_idx',
            old_name='admissions_academic_year_idx',
        ),
        migrations.RenameIndex(
            model_name='candidaturedocument',
            new_name='admissions__is_vali_121f0c_idx',
            old_name='admissions_doc_valid_idx',
        ),
        migrations.RenameIndex(
            model_name='candidaturedocument',
            new_name='admissions__documen_c07b7d_idx',
            old_name='admissions_doc_type_idx',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='academic_year',
            field=models.CharField(help_text='Année académique (ex: 2025-2026)', max_length=9),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Commentaire interne (non visible par le candidat)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='entry_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Année d’entrée dans le programme', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('under_review', 'En cours d’analyse'), ('to_complete', 'À compléter'), ('accepted', 'Acceptée'), ('accepted_with_reserve', 'Acceptée sous réserve'), ('rejected', 'Refusée')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidaturedocument',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Validé par l’administration'),
        ),
    ]
