# Generated by Django 6.0.1 on 2026-03-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TopicView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-upvotes', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-last_activity_at']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='accepted_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_topics', to='community.answer'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topics', to='community.tag'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['last_activity_at'], name='community_t_last_ac_c6a991_idx'),
        ),
        migrations.AddField(
            model_name='topicview',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.topic'),
        ),
        migrations.AddField(
            model_name='topicview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['topic'], name='community_t_topic_i_17974a_idx'),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['user'], name='community_t_user_id_5a5d91_idx'),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['ip_address'], name='community_t_ip_addr_bed989_idx'),
        ),
    ]
