# Generated by Django 6.0.1 on 2026-03-21 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_notification_community_n_user_id_12ced1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam ou publicité'), ('offensive', 'Contenu offensant ou inapproprié'), ('hors_sujet', 'Hors sujet'), ('plagiat', "Plagiat ou violation de droits d'auteur"), ('fausse_info', 'Informations fausses ou trompeuses'), ('harcelement', 'Harcèlement ou intimidation'), ('autre', 'Autre')], max_length=30)),
                ('details', models.TextField(blank=True, help_text='Détails supplémentaires (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, help_text='Notes internes du modérateur')),
                ('action_taken', models.CharField(blank=True, help_text='Action prise (ex: contenu supprimé, utilisateur averti)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.answer')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='community_r_status_1d1979_idx'), models.Index(fields=['reporter'], name='community_r_reporte_5b691c_idx'), models.Index(fields=['created_at'], name='community_r_created_dcb645_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('reporter', 'topic'), name='unique_topic_report_per_user'), models.UniqueConstraint(condition=models.Q(('answer__isnull', False)), fields=('reporter', 'answer'), name='unique_answer_report_per_user')],
            },
        ),
    ]
