# Generated by Django 6.0.1 on 2026-03-21 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('color', models.CharField(default='#6B7280', max_length=20)),
                ('category', models.CharField(choices=[('contribution', 'Contribution'), ('quality', 'Qualité'), ('votes', 'Votes'), ('author', 'Auteur'), ('streak', 'Séries'), ('special', 'Spécial')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('uncommon', 'Peu commun'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text="Ex: {'answers_count': 10}")),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Définition de badge',
                'verbose_name_plural': 'Définitions de badges',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='XPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_topic', 'Créer un sujet'), ('create_answer', 'Répondre'), ('answer_accepted', 'Réponse acceptée'), ('receive_upvote', 'Recevoir un upvote'), ('give_upvote', 'Donner un upvote'), ('daily_login', 'Connexion quotidienne'), ('streak_7days', 'Série 7 jours'), ('streak_30days', 'Série 30 jours'), ('complete_profile', 'Profil complété'), ('first_topic_of_day', '1er sujet du jour')], max_length=50, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration XP',
                'verbose_name_plural': 'Configurations XP',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('alltime', 'Tout temps')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('category', models.CharField(choices=[('xp', 'Points XP'), ('answers', 'Réponses'), ('accepted', 'Solutions')], max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('topics_created', models.PositiveIntegerField(default=0)),
                ('answers_given', models.PositiveIntegerField(default=0)),
                ('answers_accepted', models.PositiveIntegerField(default=0)),
                ('upvotes_received', models.PositiveIntegerField(default=0)),
                ('upvotes_given', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('has_custom_flair', models.BooleanField(default=False)),
                ('has_signature', models.BooleanField(default=False)),
                ('has_gold_frame', models.BooleanField(default=False)),
                ('custom_title', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Gamification',
                'verbose_name_plural': 'Profils Gamification',
                'indexes': [models.Index(fields=['total_xp'], name='community_g_total_x_0601f0_idx'), models.Index(fields=['level'], name='community_g_level_945110_idx'), models.Index(fields=['-total_xp'], name='community_g_total_x_994ab5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='community.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='community_x_user_id_1f9110_idx')],
            },
        ),
    ]
