# Generated by Django 6.0.1 on 2026-03-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_badgedefinition_xpconfig_leaderboardentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Épinglé'),
        ),
    ]
