# Generated by Django 6.0.1 on 2026-04-08 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_user_type'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_type'], name='accounts_pr_user_ty_77c9a6_idx'),
        ),
    ]
