# Generated by Django 6.0.1 on 2026-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_position'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='accounts_pr_positio_bcd247_idx',
            old_name='accounts_pr_position_250d35_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text="Presentation publique de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_domain',
            field=models.CharField(blank=True, db_index=True, help_text="Domaine principal d'activite", max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrateur'), ('executive', 'Direction'), ('admissions', 'Admissions'), ('finance', 'Finance'), ('teacher', 'Enseignant'), ('student', 'Etudiant')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('staff', 'Staff')], db_index=True, help_text='Type utilisateur normalise pour le portail', max_length=20),
        ),
    ]
