# Generated by Django 6.0.1 on 2026-04-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_accounts_pr_position_250d35_idx_accounts_pr_positio_bcd247_idx_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(db_index=True, help_text='Premier jour du mois de paie.')),
                ('base_salary', models.PositiveBigIntegerField(default=0)),
                ('allowances', models.PositiveBigIntegerField(default=0)),
                ('deductions', models.PositiveBigIntegerField(default=0)),
                ('advances', models.PositiveBigIntegerField(default=0)),
                ('paid_amount', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Pret a payer'), ('partial', 'Paiement partiel'), ('paid', 'Paye')], db_index=True, default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-period_month', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code employe interne pour la gestion de paie.', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Actif'), ('on_leave', 'En conge'), ('suspended', 'Suspendu'), ('inactive', 'Inactif')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_base',
            field=models.PositiveBigIntegerField(default=0, help_text='Salaire mensuel de base en FCFA.'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['employment_status'], name='accounts_pr_employm_b09ea5_idx'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['branch', 'period_month'], name='accounts_pa_branch__09bb46_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['employee', 'period_month'], name='accounts_pa_employe_0cfa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['status', 'period_month'], name='accounts_pa_status_be428c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('branch', 'employee', 'period_month'), name='accounts_unique_branch_employee_payroll_period'),
        ),
    ]
