# Generated by Django 6.0.1 on 2026-04-27 22:33

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payrollentry_profile_employee_code_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('rent', 'Loyer'), ('utilities', 'Eau / electricite'), ('supplies', 'Fournitures'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('communication', 'Communication'), ('other', 'Autre')], db_index=True, default='other', max_length=30)),
                ('amount', models.PositiveBigIntegerField()),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=accounts.models.branch_expense_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'A valider'), ('approved', 'Approuvee'), ('paid', 'Payee'), ('rejected', 'Rejetee')], db_index=True, default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_branch_expenses', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_expenses', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_branch_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depense annexe',
                'verbose_name_plural': 'Depenses annexes',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entree'), ('out', 'Sortie')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('expense', 'Depense'), ('payroll', 'Salaire'), ('student_payment', 'Paiement etudiant'), ('adjustment', 'Ajustement caisse')], db_index=True, default='manual', max_length=30)),
                ('amount', models.PositiveBigIntegerField()),
                ('label', models.CharField(max_length=180)),
                ('movement_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='accounts.branchexpense')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['branch', 'expense_date'], name='accounts_br_branch__29fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['branch', 'status'], name='accounts_br_branch__a71c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['category', 'expense_date'], name='accounts_br_categor_11206e_idx'),
        ),
        migrations.AddIndex(
            model_name='branchcashmovement',
            index=models.Index(fields=['branch', 'movement_date'], name='accounts_br_branch__b998a2_idx'),
        ),
        migrations.AddIndex(
            model_name='branchcashmovement',
            index=models.Index(fields=['branch', 'movement_type'], name='accounts_br_branch__335b48_idx'),
        ),
        migrations.AddIndex(
            model_name='branchcashmovement',
            index=models.Index(fields=['source', 'movement_date'], name='accounts_br_source_ca366e_idx'),
        ),
    ]
