# Generated by Django 6.0.1 on 2026-04-28 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_branchexpense_branchcashmovement_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('expense', 'Depense'), ('cash', 'Caisse')], max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequence comptable',
                'verbose_name_plural': 'Sequences comptables',
            },
        ),
        migrations.AddField(
            model_name='branchcashmovement',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='branchcashmovement',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='accounts/cash-receipts/'),
        ),
        migrations.AddField(
            model_name='branchcashmovement',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Reference technique de la source pour eviter les doublons de synchronisation.', max_length=120),
        ),
        migrations.AddIndex(
            model_name='branchcashmovement',
            index=models.Index(fields=['branch', 'source', 'source_reference'], name='accounts_br_branch__e5eb2b_idx'),
        ),
        migrations.AddField(
            model_name='accountingdocumentsequence',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_sequences', to='branches.branch'),
        ),
        migrations.AddConstraint(
            model_name='accountingdocumentsequence',
            constraint=models.UniqueConstraint(fields=('branch', 'document_type', 'year'), name='accounts_unique_accounting_sequence_branch_type_year'),
        ),
    ]
