# Generated by Django 6.0.1 on 2026-04-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountingdocumentsequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcashmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('expense', 'Depense'), ('payroll', 'Salaire'), ('student_payment', 'Paiement etudiant'), ('shop', 'Boutique'), ('adjustment', 'Ajustement caisse')], db_index=True, default='manual', max_length=30),
        ),
    ]
