# Generated by Django 6.0.1 on 2026-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollentry',
            name='status',
            field=models.CharField(choices=[('draft', 'A verifier'), ('ready', 'Disponible a retirer'), ('partial', 'Retrait partiel'), ('paid', 'Retire')], db_index=True, default='draft', max_length=20),
        ),
    ]
