# Generated by Django 6.0.1 on 2026-05-14 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_payrollentry_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Adresse postale ou administrative principale.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Numero de contact principal de l'utilisateur.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_in_app", models.BooleanField(default=True)),
                ("notify_sms", models.BooleanField(default=False)),
                ("ui_sidebar_collapsed", models.BooleanField(default=False)),
                ("ui_compact_mode", models.BooleanField(default=False)),
                ("ui_autorefresh", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(db_index=True, on_delete=models.CASCADE, related_name="user_preference", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Preference utilisateur",
                "verbose_name_plural": "Preferences utilisateurs",
            },
        ),
    ]
