# Generated by Django 6.0.5 on 2026-05-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_position_dga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('student', 'Etudiant'), ('teacher', 'Enseignant'), ('finance_manager', 'Responsable finance'), ('payment_agent', 'Agent de paiement'), ('secretary', 'Secretaire'), ('admissions', 'Admissions'), ('director_of_studies', 'Directeur des etudes'), ('executive_director', 'Direction executive'), ('deputy_executive_director', 'Direction generale adjointe'), ('branch_manager', 'Gestionnaire annexe'), ('academic_supervisor', 'Surveillant academique'), ('it_support', 'Informaticien'), ('marketing_manager', 'Responsable marketing digital'), ('super_admin', 'Super administrateur')], db_index=True, help_text='Fonction metier principale pour le routage dashboard.', max_length=40),
        ),
    ]
