# Generated by Django 6.0.1 on 2026-05-29 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_profile_position"),
        ("branches", "0002_branch_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="teacher_hourly_rate",
            field=models.PositiveBigIntegerField(default=0, help_text="Tarif horaire officiel pour les enseignants, en FCFA."),
        ),
        migrations.AlterField(
            model_name="branchcashmovement",
            name="source",
            field=models.CharField(choices=[("manual", "Saisie manuelle"), ("expense", "Depense"), ("payroll", "Salaire"), ("honorarium", "Honoraire enseignant"), ("student_payment", "Paiement etudiant"), ("shop", "Boutique"), ("adjustment", "Ajustement caisse")], db_index=True, default="manual", max_length=30),
        ),
        migrations.CreateModel(
            name="TeacherHonorariumEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.DateField(db_index=True, help_text="Premier jour du mois des honoraires.")),
                ("hourly_rate", models.PositiveBigIntegerField(default=0)),
                ("validated_hours", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("adjustments", models.PositiveBigIntegerField(default=0)),
                ("deductions", models.PositiveBigIntegerField(default=0)),
                ("advances", models.PositiveBigIntegerField(default=0)),
                ("paid_amount", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(choices=[("draft", "A verifier"), ("ready", "Disponible a retirer"), ("partial", "Retrait partiel"), ("paid", "Retire")], db_index=True, default="draft", max_length=20)),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teacher_honorarium_entries", to="branches.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_teacher_honorariums", to=settings.AUTH_USER_MODEL)),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teacher_honorarium_entries", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_teacher_honorariums", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Honoraire enseignant",
                "verbose_name_plural": "Honoraires enseignants",
                "ordering": ["-period_month", "teacher__last_name", "teacher__first_name"],
            },
        ),
        migrations.CreateModel(
            name="BranchMonthlyClosure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.DateField(db_index=True)),
                ("total_entries", models.PositiveBigIntegerField(default=0)),
                ("total_exits", models.PositiveBigIntegerField(default=0)),
                ("student_revenue", models.PositiveBigIntegerField(default=0)),
                ("shop_revenue", models.PositiveBigIntegerField(default=0)),
                ("salary_paid", models.PositiveBigIntegerField(default=0)),
                ("honorarium_paid", models.PositiveBigIntegerField(default=0)),
                ("expenses_paid", models.PositiveBigIntegerField(default=0)),
                ("result_amount", models.BigIntegerField(default=0)),
                ("bank_transfer_amount", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(choices=[("draft", "Brouillon"), ("validated", "Validee"), ("closed", "Cloturee")], db_index=True, default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="monthly_closures", to="branches.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_monthly_closures", to=settings.AUTH_USER_MODEL)),
                ("validated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="validated_monthly_closures", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Cloture mensuelle",
                "verbose_name_plural": "Clotures mensuelles",
                "ordering": ["-period_month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BranchBankTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_name", models.CharField(max_length=180)),
                ("reference", models.CharField(db_index=True, max_length=120)),
                ("transfer_date", models.DateField(db_index=True)),
                ("amount", models.PositiveBigIntegerField()),
                ("proof", models.FileField(blank=True, null=True, upload_to="accounts/bank-transfers/")),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bank_transfers", to="branches.branch")),
                ("closure", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="bank_transfer", to="accounts.branchmonthlyclosure")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_bank_transfers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Versement bancaire",
                "verbose_name_plural": "Versements bancaires",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="teacherhonorariumentry",
            constraint=models.UniqueConstraint(fields=("branch", "teacher", "period_month"), name="accounts_unique_branch_teacher_honorarium_period"),
        ),
        migrations.AddConstraint(
            model_name="branchmonthlyclosure",
            constraint=models.UniqueConstraint(fields=("branch", "period_month"), name="accounts_unique_branch_monthly_closure_period"),
        ),
        migrations.AddIndex(
            model_name="teacherhonorariumentry",
            index=models.Index(fields=["branch", "period_month"], name="accounts_te_branch__0db0d2_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherhonorariumentry",
            index=models.Index(fields=["teacher", "period_month"], name="accounts_te_teacher_a1444e_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherhonorariumentry",
            index=models.Index(fields=["status", "period_month"], name="accounts_te_status_c00137_idx"),
        ),
        migrations.AddIndex(
            model_name="branchmonthlyclosure",
            index=models.Index(fields=["branch", "period_month"], name="accounts_br_branch__63518b_idx"),
        ),
        migrations.AddIndex(
            model_name="branchmonthlyclosure",
            index=models.Index(fields=["branch", "status"], name="accounts_br_branch__2c8bac_idx"),
        ),
        migrations.AddIndex(
            model_name="branchbanktransfer",
            index=models.Index(fields=["branch", "transfer_date"], name="accounts_br_branch__2a7526_idx"),
        ),
        migrations.AddIndex(
            model_name="branchbanktransfer",
            index=models.Index(fields=["reference"], name="accounts_br_referen_dc4e45_idx"),
        ),
    ]
