# Generated by Django 6.0.5 on 2026-05-31 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teacher_honorarium_branch_closure_and_bank_transfer'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcashmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('expense', 'Depense'), ('payroll', 'Salaire'), ('honorarium', 'Honoraire enseignant'), ('student_payment', 'Paiement etudiant'), ('shop', 'Boutique'), ('adjustment', 'Ajustement caisse'), ('donation', 'Don / Donation')], db_index=True, default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(db_index=True, help_text='Nom du donateur / organisation.', max_length=200)),
                ('amount', models.PositiveBigIntegerField(help_text='Montant du don en FCFA.')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('motif', models.CharField(choices=[('sponsoring', 'Sponsoring / Partenariat'), ('mecenat', 'Mecenat'), ('appui', 'Appui institutionnel'), ('projet', 'Projet / Programme'), ('bourse', 'Bourse etudiant'), ('infrastructure', 'Infrastructure / Equipement'), ('evenement', 'Evenement / Activite'), ('libre', 'Don libre'), ('autre', 'Autre')], db_index=True, default='libre', max_length=40)),
                ('payment_method', models.CharField(choices=[('cash', 'Especes'), ('orange_money', 'Orange Money'), ('t-money', 'T-Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description ou remerciements.')),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='Numero de recu.', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='branches.branch')),
                ('cash_movement', models.OneToOneField(blank=True, help_text='Mouvement de caisse lié (entrée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_source', to='accounts.branchcashmovement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Don / Donation',
                'verbose_name_plural': 'Dons / Donations',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='accounts_do_branch__0b9d0c_idx'), models.Index(fields=['branch', 'motif'], name='accounts_do_branch__f8fed9_idx'), models.Index(fields=['donor_name'], name='accounts_do_donor_n_a176b4_idx')],
            },
        ),
    ]
