# Generated by Django 6.0.5 on 2026-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_branchcashmovement_source_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='internal_rules_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
