# Generated by Django 6.0.5 on 2026-06-18 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_userpreference_internal_rules_accepted_at"),
        ("branches", "0002_branch_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveActionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("payment_edit", "Modification d'un paiement valide"),
                            ("payment_cancel", "Annulation d'un paiement valide"),
                            (
                                "payroll_edit",
                                "Modification d'une fiche de paie deja payee",
                            ),
                            (
                                "honorarium_edit",
                                "Modification d'un honoraire deja paye",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Nom du modele cible (ex: Payment).", max_length=60
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Motif explique par la gestionnaire."
                    ),
                ),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("requested_state", models.JSONField(blank=True, default=dict)),
                ("otp_code_hash", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("approved", "Validee"),
                            ("expired", "Expiree"),
                            ("cancelled", "Annulee"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_action_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitive_action_requests",
                        to="branches.branch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitive_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'action sensible",
                "verbose_name_plural": "Demandes d'action sensible",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=30)),
                ("target_model", models.CharField(max_length=60)),
                ("target_id", models.PositiveBigIntegerField()),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("new_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_audit_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_audit_logs",
                        to="branches.branch",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sensitive_action_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="accounts.sensitiveactionrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit financier",
                "verbose_name_plural": "Logs d'audit financier",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sensitiveactionrequest",
            index=models.Index(
                fields=["branch", "status"], name="accounts_se_branch__0205ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensitiveactionrequest",
            index=models.Index(
                fields=["target_model", "target_id"],
                name="accounts_se_target__900b87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialauditlog",
            index=models.Index(
                fields=["branch", "created_at"], name="accounts_fi_branch__5b0965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialauditlog",
            index=models.Index(
                fields=["target_model", "target_id"],
                name="accounts_fi_target__61d574_idx",
            ),
        ),
    ]
