# Generated by Django 6.0.5 on 2026-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_sensitiveactionrequest_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcashmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('expense', 'Depense'), ('payroll', 'Salaire'), ('honorarium', 'Honoraire enseignant'), ('student_payment', 'Paiement etudiant'), ('shop', 'Boutique'), ('bank_transfer', 'Versement bancaire'), ('adjustment', 'Ajustement caisse'), ('donation', 'Don / Donation')], db_index=True, default='manual', max_length=30),
        ),
    ]
