# Generated by Django 6.0.5 on 2026-08-22 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_cards_hardening_and_staff'),
        ('branches', '0003_branch_cash_reserve_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('opening_amount', models.PositiveBigIntegerField(default=0)),
                ('system_opening_balance', models.BigIntegerField(default=0)),
                ('expected_amount', models.BigIntegerField(default=0)),
                ('counted_amount', models.BigIntegerField(blank=True, null=True)),
                ('difference_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermee')], db_index=True, default='open', max_length=12)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='branchcashmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('branch', 'source', 'source_reference'), name='accounts_unique_cash_source_reference'),
        ),
        migrations.AddField(
            model_name='branchcashregistersession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_sessions', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='branchcashregistersession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_register_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchcashregistersession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cash_register_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='branchcashregistersession',
            index=models.Index(fields=['branch', 'status', 'session_date'], name='accounts_br_branch__1dacf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchcashregistersession',
            constraint=models.UniqueConstraint(fields=('branch', 'session_date'), name='accounts_unique_branch_cash_register_day'),
        ),
    ]
