# Generated by Django 6.0.5 on 2026-08-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_branchcashregistersession_and_more'),
        ('branches', '0003_branch_cash_reserve_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_type', models.CharField(choices=[('receipt', 'Encaissement'), ('disbursement', 'Decaissement')], db_index=True, max_length=16)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('nature', models.CharField(choices=[('recurring', 'Recurrente'), ('temporary', 'Temporaire')], default='recurring', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('planned_closure_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Cloturee'), ('archived', 'Archivee')], db_index=True, default='active', max_length=16)),
                ('is_favorite', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_branch_wallets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchWalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Credit'), ('out', 'Debit')], max_length=4)),
                ('kind', models.CharField(choices=[('allocation', 'Affectation'), ('receipt_allocation', 'Affectation recette'), ('transfer', 'Transfert'), ('return', 'Restitution'), ('consumption', 'Utilisation'), ('reversal', 'Contre-ecriture')], db_index=True, max_length=24)),
                ('amount', models.PositiveBigIntegerField()),
                ('operation_reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='accounts.branchcashmovement')),
                ('counterpart_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_entries', to='accounts.branchwallet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.branchwallet')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='branchwallet',
            index=models.Index(fields=['branch', 'status', 'wallet_type'], name='accounts_br_branch__3d563e_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchwallet',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='accounts_unique_branch_wallet_name'),
        ),
        migrations.AddIndex(
            model_name='branchwalletentry',
            index=models.Index(fields=['wallet', 'direction', 'created_at'], name='accounts_br_wallet__036795_idx'),
        ),
        migrations.AddIndex(
            model_name='branchwalletentry',
            index=models.Index(fields=['operation_reference'], name='accounts_br_operati_de4750_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchwalletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('wallet', 'idempotency_key'), name='accounts_unique_wallet_entry_idempotency'),
        ),
    ]
