# Generated by Django 6.0.5 on 2026-08-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_branch_wallets'),
        ('branches', '0003_branch_cash_reserve_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSignatureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('payroll', 'Salaire'), ('honorarium', 'Honoraire')], db_index=True, max_length=20)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('initiated', 'Initiee'), ('awaiting_signature', 'En attente de signature'), ('signed', 'Signee'), ('completed', 'Payee'), ('refused', 'Refusee'), ('expired', 'Expiree'), ('cancelled', 'Annulee')], db_index=True, default='initiated', max_length=30)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('signature_data', models.TextField(blank=True)),
                ('signature_sha256', models.CharField(blank=True, max_length=64)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.CharField(blank=True, max_length=300)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_signature_sessions', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_signature_sessions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_signature_sessions', to='branches.branch')),
                ('cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_signature_sessions', to='accounts.branchcashmovement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_signature_sessions', to=settings.AUTH_USER_MODEL)),
                ('honorarium_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_sessions', to='accounts.teacherhonorariumentry')),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_sessions', to='accounts.payrollentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='accounts_pa_branch__8b8dd3_idx'), models.Index(fields=['beneficiary', 'status', 'expires_at'], name='accounts_pa_benefic_923039_idx')],
            },
        ),
    ]
