# Generated by Django 6.0.5 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_paymentsignaturesession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitiveactionrequest",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("payment_edit", "Modification d'un paiement valide"),
                    ("payment_cancel", "Annulation d'un paiement valide"),
                    ("payroll_edit", "Modification d'une fiche de paie deja payee"),
                    ("honorarium_edit", "Modification d'un honoraire deja paye"),
                    ("semester_publish", "Publication des resultats d'un semestre"),
                    ("annual_deliberation_publish", "Publication d'une deliberation annuelle"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
