# Generated by Django 6.0.5 on 2026-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="cash_reserve_target",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant a conserver en caisse a chaque cloture mensuelle pour couvrir les depenses imprevues du mois suivant. Le versement bancaire suggere est calcule en consequence.",
                max_digits=12,
                verbose_name="Fonds de roulement cible",
            ),
        ),
    ]
