# Generated by Django 6.0.5 on 2026-05-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='communicati_provide_34d2ea_idx',
            old_name='communicati_provider_5ad62a_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='communicati_channel_3b75b0_idx',
            old_name='communicati_channel_49c6e7_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='communicati_event_t_ba29f5_idx',
            old_name='communicati_event_t_7ac77b_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='communicati_source__7fc448_idx',
            old_name='communicati_source__e722d5_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='communicati_status_41309e_idx',
            old_name='communicati_status_0f0b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='communicati_recipie_5aa8ef_idx',
            old_name='communicati_recipie_0d5608_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationnotification',
            new_name='communicati_recipie_d109d6_idx',
            old_name='communicati_recipie_ba782d_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationnotification',
            new_name='communicati_channel_b47010_idx',
            old_name='communicati_channel_9547cb_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationnotification',
            new_name='communicati_event_t_edee73_idx',
            old_name='communicati_event_t_4f092a_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationnotification',
            new_name='communicati_legacy__8a909e_idx',
            old_name='communicati_legacy__4ec0ab_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='communicati_convers_94d19b_idx',
            old_name='communicati_convers_1ac95d_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='communicati_updated_ffac35_idx',
            old_name='communicati_updated_7f68a3_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmessage',
            new_name='communicati_convers_381a5e_idx',
            old_name='communicati_convers_3d150a_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmessage',
            new_name='communicati_author__1511d5_idx',
            old_name='communicati_author__d16053_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='communicati_user_id_e2cdea_idx',
            old_name='communicati_user_id_9b4dcd_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='communicati_convers_2b9a5a_idx',
            old_name='communicati_convers_d86e02_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereadreceipt',
            new_name='communicati_partici_3e9258_idx',
            old_name='communicati_partici_2d6cd3_idx',
        ),
    ]
