# Generated by Django 6.0.1 on 2026-04-28 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_image'),
        ('formations', '0008_delete_programavailability'),
        ('inscriptions', '0005_alter_statushistory_options_inscription_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_payment', 'En attente paiement'), ('paid', 'Payee'), ('ready', 'Prete a retirer'), ('delivered', 'Remise'), ('cancelled', 'Annulee')], db_index=True, default='draft', max_length=30)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_orders', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_shop_orders', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to='inscriptions.inscription')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Valide'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='shop/receipts/')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.shoporder')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('uniform', 'Tenue'), ('blouse', 'Blouse'), ('fabric', 'Tissu'), ('badge', 'Badge'), ('kit', 'Kit'), ('other', 'Autre')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.PositiveBigIntegerField()),
                ('is_required', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_products', to='branches.branch')),
                ('programmes', models.ManyToManyField(blank=True, related_name='shop_products', to='formations.programme')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('extra_price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.shopproduct')),
            ],
            options={
                'ordering': ['product', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveBigIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.shopproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.shopproductvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('stock', 'Stock')], max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_sequences', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ShopStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entree'), ('out', 'Sortie'), ('adjustment', 'Ajustement')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_stock_movements', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='shop.shoporder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shop.shopproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shop.shopproductvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['branch', 'status'], name='shop_shopor_branch__27ebbe_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['student', 'status'], name='shop_shopor_student_d64257_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppayment',
            index=models.Index(fields=['order', 'status'], name='shop_shoppa_order_i_75d2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppayment',
            index=models.Index(fields=['status', 'paid_at'], name='shop_shoppa_status_e305ca_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['branch', 'category'], name='shop_shoppr_branch__3b9608_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['branch', 'is_required', 'is_active'], name='shop_shoppr_branch__1afd46_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopproductvariant',
            constraint=models.UniqueConstraint(fields=('product', 'label'), name='shop_unique_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='shopsequence',
            constraint=models.UniqueConstraint(fields=('branch', 'sequence_type', 'year'), name='shop_unique_sequence_branch_type_year'),
        ),
        migrations.AddIndex(
            model_name='shopstockmovement',
            index=models.Index(fields=['branch', 'product'], name='shop_shopst_branch__48a5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shopstockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='shop_shopst_movemen_3bd7cf_idx'),
        ),
    ]
