# Generated by Django 6.0.1 on 2026-05-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_cash_session_and_payment_agent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopcashpaymentsession',
            new_name='shop_shopca_expires_9e1c65_idx',
            old_name='shop_shopcas_expires_6918b4_idx',
        ),
        migrations.RenameIndex(
            model_name='shopcashpaymentsession',
            new_name='shop_shopca_is_used_ee1b11_idx',
            old_name='shop_shopcas_is_used_8f91e7_idx',
        ),
        migrations.RenameIndex(
            model_name='shopcashpaymentsession',
            new_name='shop_shopca_agent_i_994e91_idx',
            old_name='shop_shopcas_agent_i_62e6f5_idx',
        ),
        migrations.RenameIndex(
            model_name='shopcashpaymentsession',
            new_name='shop_shopca_order_i_748852_idx',
            old_name='shop_shopcas_order_i_d4ae18_idx',
        ),
    ]
