# Generated by Django 6.0.5 on 2026-06-19 08:33

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0008_delete_programavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('auteurs', models.CharField(help_text='Auteur(s) du mémoire', max_length=300)),
                ('encadreur', models.CharField(blank=True, max_length=200)),
                ('niveau', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('resume', models.TextField(help_text='Résumé / abstract affiché publiquement (HTML autorisé).')),
                ('mots_cles', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=300)),
                ('fichier_source', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\PycharmProjects\\esfe-core\\private_media\\memoires'), upload_to='memoires/sources/')),
                ('nb_pages', models.PositiveIntegerField(default=0)),
                ('est_mis_en_avant', models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], db_index=True, default='brouillon', max_length=20)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('date_depot', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_deposes', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memoires', to='formations.filiere')),
            ],
            options={
                'verbose_name': 'Mémoire',
                'verbose_name_plural': 'Mémoires',
                'ordering': ['-date_publication', '-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='memoires.memoire')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='PageMemoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\PycharmProjects\\esfe-core\\private_media\\memoires'), upload_to='memoires/pages/')),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='memoires.memoire')),
            ],
            options={
                'verbose_name': 'Page de mémoire',
                'verbose_name_plural': 'Pages de mémoire',
                'ordering': ['numero'],
            },
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['statut', 'niveau'], name='memoires_me_statut_5b6518_idx'),
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['-nombre_vues'], name='memoires_me_nombre__d848ab_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationlog',
            index=models.Index(fields=['memoire', 'date'], name='memoires_co_memoire_ad1237_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagememoire',
            constraint=models.UniqueConstraint(fields=('memoire', 'numero'), name='unique_page_par_memoire'),
        ),
    ]
