# Generated by Django 6.0.5 on 2026-06-19 10:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='resume',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Résumé / abstract affiché publiquement.', verbose_name='Résumé'),
        ),
    ]
