# Generated by Django 6.0.5 on 2026-07-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0002_alter_memoire_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoireFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='memoires.memoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires_favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('user', 'memoire'), name='unique_favori_user_memoire')],
            },
        ),
    ]
