# Generated by Django 6.0.5 on 2026-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0003_memoirefavori'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='image',
            field=models.ImageField(blank=True, help_text='Image affichée dans la liste et la fiche du mémoire.', null=True, upload_to='memoires/couvertures/', verbose_name='Image de couverture'),
        ),
    ]
