from django.urls import path

import secretary.views as views

app_name = "secretary"

urlpatterns = [
    path("", views.secretary_dashboard, name="secretary_dashboard"),
    path("profile/update/", views.secretary_profile_update, name="profile_update"),
    path("preferences/update/", views.secretary_preferences_update, name="preferences_update"),
    path("htmx/command-palette/", views.htmx_command_palette, name="htmx_command_palette"),
    path("htmx/students/", views.htmx_student_results, name="htmx_student_results"),
    path("htmx/classes/", views.htmx_class_results, name="htmx_class_results"),
    path("htmx/classes/<int:class_id>/students/", views.htmx_class_students, name="htmx_class_students"),
    path("htmx/registry/", views.htmx_registry_results, name="htmx_registry_results"),
    path("htmx/appointments/", views.htmx_appointment_results, name="htmx_appointment_results"),
    path("htmx/documents/", views.htmx_document_results, name="htmx_document_results"),
    path("htmx/tasks/", views.htmx_task_results, name="htmx_task_results"),
    path("htmx/messages/", views.htmx_messages_panel, name="htmx_messages_panel"),
    path("htmx/dashboard/scope/", views.htmx_dashboard_scope, name="htmx_dashboard_scope"),
    path("htmx/dashboard/kpis/", views.htmx_dashboard_kpis, name="htmx_dashboard_kpis"),
    path("htmx/dashboard/sidebar-counters/", views.htmx_sidebar_counters, name="htmx_sidebar_counters"),
    path("htmx/dashboard/overview-registry/", views.htmx_overview_registry, name="htmx_overview_registry"),
    path("htmx/dashboard/overview-appointments/", views.htmx_overview_appointments, name="htmx_overview_appointments"),
    path("htmx/dashboard/overview-visits/", views.htmx_overview_visits, name="htmx_overview_visits"),
    path("htmx/dashboard/overview-tasks/", views.htmx_overview_tasks, name="htmx_overview_tasks"),
    path("htmx/dashboard/visits-open/", views.htmx_visits_open, name="htmx_visits_open"),
    path("htmx/dashboard/appointments-today/", views.htmx_appointments_today, name="htmx_appointments_today"),
    path("htmx/dashboard/documents-pending/", views.htmx_documents_pending, name="htmx_documents_pending"),
    path("reports/daily-registry/", views.daily_registry_report, name="daily_registry_report"),
    path("registry/", views.registry_list, name="registry_list"),
    path("registry/kanban/", views.registry_kanban, name="registry_kanban"),
    path("registry/<int:pk>/move/<str:new_status>/", views.registry_kanban_move, name="registry_kanban_move"),
    path("registry/create/", views.registry_create, name="registry_create"),
    path("registry/<int:pk>/update/", views.registry_update, name="registry_update"),
    path("registry/<int:pk>/detail/", views.registry_detail, name="registry_detail"),
    path("registry/<int:pk>/start/", views.registry_start, name="registry_start"),
    path("registry/<int:pk>/processed/", views.registry_mark_processed, name="registry_mark_processed"),
    path("registry/<int:pk>/archive/", views.registry_archive, name="registry_archive"),
    path("appointment/", views.appointment_list, name="appointment_list"),
    path("appointment/create/", views.appointment_create, name="appointment_create"),
    path("appointment/<int:pk>/update/", views.appointment_update, name="appointment_update"),
    path("appointment/<int:pk>/complete/", views.appointment_complete, name="appointment_complete"),
    path("appointment/<int:pk>/archive/", views.appointment_archive, name="appointment_archive"),
    path("visitor/", views.visitor_list, name="visitor_list"),
    path("visitor/create/", views.visitor_create, name="visitor_create"),
    path("visitor/<int:pk>/update/", views.visitor_update, name="visitor_update"),
    path("visitor/<int:pk>/complete/", views.visitor_complete, name="visitor_complete"),
    path("document-receipt/", views.document_receipt_list, name="document_receipt_list"),
    path("document-receipt/create/", views.document_receipt_create, name="document_receipt_create"),
    path("document-receipt/<int:pk>/update/", views.document_receipt_update, name="document_receipt_update"),
    path("document-receipt/<int:pk>/start/", views.document_receipt_start, name="document_receipt_start"),
    path("document-receipt/<int:pk>/archive/", views.document_receipt_archive, name="document_receipt_archive"),
    path("task/", views.task_list, name="task_list"),
    path("task/create/", views.task_create, name="task_create"),
    path("task/<int:pk>/update/", views.task_update, name="task_update"),
    path("task/<int:pk>/start/", views.task_start, name="task_start"),
    path("task/<int:pk>/complete/", views.task_complete, name="task_complete"),
    path("students/<int:student_id>/snapshot/", views.student_snapshot_view, name="student_snapshot"),
]
