from django.urls import path

from portal.views import (
    admin_grade_dashboard,
    class_grade_sheet_pdf_view,
    class_grade_sheet_print_view,
    it_notes_grid_view,
    it_notes_workspace_view,
    load_grades_table,
    load_student_results,
    publish_semester_view,
    save_grade,
    save_grade_confirm_otp,
)
from portal.views.admin_grades import excel_grade_view
from portal.views.it_grades_import import it_grades_import_view
from portal.views.it_surveillance import (
    it_surveillance_student_followup_view,
    it_surveillance_workspace_view,
    surveillance_general_api_view,
)
from portal.views.reenrollment import (
    reenrollment_decision_action,
    reenrollment_propose,
    reenrollment_workspace,
)
from portal.views.it_workflows import (
    it_accounts_flow_workspace,
    it_accounts_flow_action,
    it_audit_workspace,
    it_archive_detail,
    it_archives_action,
    it_archives_workspace,
    it_branch_settings_workspace,
    it_branch_settings_save,
    it_cards_workspace,
    it_class_cards_pdf,
    it_catalog_action,
    it_catalog_workspace,
    it_export_notes_excel,
    it_home_workspace,
    it_import_upload,
    it_import_workspace,
    it_my_account_workspace,
    it_my_account_save,
    it_notes_decisions,
    it_notes_flow_workspace,
    it_notes_kpi,
    it_notes_retake_modal,
    it_workflow_section,
    it_notes_workflow_action,
    it_notifications_workspace,
    it_notifications_action,
    it_structure_drawer,
    it_structure_action,
    it_structure_modal,
    it_structure_workspace,
    it_student_card_pdf,
    it_supervision_workspace,
    it_support_flow_action,
    it_support_flow_workspace,
    it_user_modal,
    it_user_modal_save,
    load_notes_workspace,
)
from portal.views.supervisor_cases import (
    supervisor_cases_workspace,
    supervisor_case_detail,
    supervisor_case_create,
    supervisor_case_advance,
    supervisor_case_add_note,
    supervisor_student_cases,
)
from portal.views.supervisor import (
    supervisor_assign_replacement,
    supervisor_attendance_toggle_student,
    supervisor_class_detail,
    supervisor_convocation_create,
    supervisor_convocation_drawer,
    supervisor_create_schedule_event,
    supervisor_mark_student_attendance,
    supervisor_mark_teacher_attendance,
    supervisor_month_materialize,
    supervisor_planner_hub,
    supervisor_planner_view_workspace,
    supervisor_planner_workspace,
    supervisor_portal,
    supervisor_quick_course_create,
    supervisor_quick_search,
    supervisor_save_lesson_log,
    supervisor_signal_teacher_incident,
    supervisor_student_drawer,
    supervisor_student_options,
    supervisor_teacher_drawer,
    supervisor_toggle_teacher_presence,
    supervisor_week_materialize,
    supervisor_weekly_slot_save,
    supervisor_weekly_slots_workspace,
    supervisor_workflow_roll_action,
    supervisor_workflow_workspace,
)
from portal.views.views import (
    admissions_portal,
    director_correspondance_create,
    director_correspondance_pdf,
    director_correspondance_publish,
    director_programme_action,
    dg_action,
    dg_assign_manager_modal,
    dg_closure_detail,
    dg_diploma_action,
    dg_drawer,
    dg_exec_action,
    dg_export,
    dg_modal,
    dg_portal,
    dg_recruit_staff,
    dg_section,
    director_portal,
    director_drawer,
    schedule_class_print,
    schedule_teacher_print,
    director_teacher_contract_download,
    director_teacher_create,
    director_teacher_assign,
    director_teacher_documents_modal,
    director_teacher_document_upload,
    director_teacher_document_review,
    director_export_report_xlsx,
    director_planner_hub,
    director_planner_view_workspace,
    director_planner_workspace,
    director_results_confirm_otp,
    director_weekly_slots_workspace,
    director_weekly_slot_save,
    director_week_materialize,
    director_month_materialize,
    director_create_schedule_event,
    director_transfer_create,
    director_transfer_review,
    director_results_action,
    director_results_confirm_otp,
    director_bulletin_action,
    director_workspace,
    finance_portal,
    it_accounts_panel,
    it_assign_ticket,
    it_comment_ticket,
    it_create_ticket,
    it_diagnostics_panel,
    it_portal,
    it_reactivate_account,
    it_reset_password,
    it_support_panel,
    it_suspend_account,
    it_toggle_account,
    it_unblock_account,
    it_update_account_email,
    it_update_ticket_status,
    portal_dashboard,
    portal_home,
    secretary_portal,
    staff_portal,
    student_portal,
    teacher_portal,
    teacher_class_detail,
    teacher_content_viewer,
    teacher_lesson_log_panel,
    teacher_settings_workspace,
    teacher_support_workspace,
)

app_name = "accounts_portal"

urlpatterns = [
    path("", portal_home, name="portal_home"),
    path("dashboard/", portal_dashboard, name="portal_dashboard"),
    path("schedule/print/class/<int:class_id>/", schedule_class_print, name="schedule_class_print"),
    path("schedule/print/teacher/<int:teacher_id>/", schedule_teacher_print, name="schedule_teacher_print"),
    path("student/", student_portal, name="portal_student"),
    path("staff/", staff_portal, name="portal_staff"),
    path("teacher/", teacher_portal, name="portal_teacher"),
    path("teacher/classes/<int:class_id>/", teacher_class_detail, name="teacher_class_detail"),
    path("teacher/supports/", teacher_support_workspace, name="teacher_support_workspace"),
    path("teacher/settings/", teacher_settings_workspace, name="teacher_settings_workspace"),
    path("teacher/events/<int:event_id>/lesson-log/", teacher_lesson_log_panel, name="teacher_lesson_log_panel"),
    path("teacher/content/<int:content_id>/view/", teacher_content_viewer, name="teacher_content_viewer"),
    path("finance/", finance_portal, name="portal_finance"),
    path("secretary/", secretary_portal, name="portal_secretary"),
    path("admissions/", admissions_portal, name="portal_admissions"),
    path("director/", director_portal, name="portal_director"),
    path("director/workspace/", director_workspace, name="director_workspace"),
    path("director/drawer/", director_drawer, name="director_drawer"),
    path("director/teachers/create/", director_teacher_create, name="director_teacher_create"),
    path("director/teachers/assign/", director_teacher_assign, name="director_teacher_assign"),
    path("director/teachers/<int:teacher_id>/contract/", director_teacher_contract_download, name="director_teacher_contract_download"),
    path("director/teachers/documents/modal/", director_teacher_documents_modal, name="director_teacher_documents_modal"),
    path("director/teachers/documents/upload/", director_teacher_document_upload, name="director_teacher_document_upload"),
    path("director/teachers/documents/review/", director_teacher_document_review, name="director_teacher_document_review"),
    path("director/programme/action/", director_programme_action, name="director_programme_action"),
    path("director/correspondances/create/", director_correspondance_create, name="director_correspondance_create"),
    path("director/correspondances/<int:doc_id>/pdf/", director_correspondance_pdf, name="director_correspondance_pdf"),
    path("director/correspondances/<int:doc_id>/publish/", director_correspondance_publish, name="director_correspondance_publish"),
    path("director/transfers/create/", director_transfer_create, name="director_transfer_create"),
    path("director/transfers/review/", director_transfer_review, name="director_transfer_review"),
    path("director/results/action/", director_results_action, name="director_results_action"),
    path("director/results/confirm-otp/", director_results_confirm_otp, name="director_results_confirm_otp"),
    path("director/bulletins/action/", director_bulletin_action, name="director_bulletin_action"),
    path("director/export/report/xlsx/", director_export_report_xlsx, name="director_export_report_xlsx"),
    path("director/planner/hub/", director_planner_hub, name="director_planner_hub"),
    path("director/planner/view/", director_planner_view_workspace, name="director_planner_view_workspace"),
    path("director/planner/workspace/", director_planner_workspace, name="director_planner_workspace"),
    path(
        "director/classes/<int:class_id>/weekly-slots/",
        director_weekly_slots_workspace,
        name="director_weekly_slots_workspace",
    ),
    path(
        "director/classes/<int:class_id>/weekly-slots/save/",
        director_weekly_slot_save,
        name="director_weekly_slot_save",
    ),
    path(
        "director/classes/<int:class_id>/weekly-slots/materialize/week/",
        director_week_materialize,
        name="director_week_materialize",
    ),
    path(
        "director/classes/<int:class_id>/weekly-slots/materialize/month/",
        director_month_materialize,
        name="director_month_materialize",
    ),
    path(
        "director/classes/<int:class_id>/schedule/create/",
        director_create_schedule_event,
        name="director_create_schedule_event",
    ),
    path("dg/", dg_portal, name="portal_dg"),
    path("dg/section/<str:section>/", dg_section, name="dg_section"),
    path("dg/drawer/", dg_drawer, name="dg_drawer"),
    path("dg/modal/", dg_modal, name="dg_modal"),
    path("dg/recruit-staff/", dg_recruit_staff, name="dg_recruit_staff"),
    path("dg/action/", dg_action, name="dg_action"),
    path("dg/exec-action/", dg_exec_action, name="dg_exec_action"),
    path("dg/assign-manager/", dg_assign_manager_modal, name="dg_assign_manager_modal"),
    path("dg/closure-detail/", dg_closure_detail, name="dg_closure_detail"),
    path("dg/diplomas/action/", dg_diploma_action, name="dg_diploma_action"),
    path("dg/export/", dg_export, name="dg_export"),
    path("supervisor/", supervisor_portal, name="portal_supervisor"),
    path("supervisor/search/", supervisor_quick_search, name="supervisor_quick_search"),
    path(
        "supervisor/classes/<int:class_id>/",
        supervisor_class_detail,
        name="supervisor_class_detail",
    ),
    path(
        "supervisor/planner/hub/",
        supervisor_planner_hub,
        name="supervisor_planner_hub",
    ),
    path(
        "supervisor/planner/view/",
        supervisor_planner_view_workspace,
        name="supervisor_planner_view_workspace",
    ),
    path(
        "supervisor/planner/workspace/",
        supervisor_planner_workspace,
        name="supervisor_planner_workspace",
    ),
    path(
        "supervisor/classes/<int:class_id>/schedule/create/",
        supervisor_create_schedule_event,
        name="supervisor_create_schedule_event",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/save/",
        supervisor_weekly_slot_save,
        name="supervisor_weekly_slot_save",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/materialize/",
        supervisor_week_materialize,
        name="supervisor_week_materialize",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/materialize/month/",
        supervisor_month_materialize,
        name="supervisor_month_materialize",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/",
        supervisor_weekly_slots_workspace,
        name="supervisor_weekly_slots_workspace",
    ),
    path(
        "supervisor/student-options/",
        supervisor_student_options,
        name="supervisor_student_options",
    ),
    path(
        "supervisor/workspace/",
        supervisor_workflow_workspace,
        name="supervisor_workflow_workspace",
    ),
    path(
        "supervisor/attendance/toggle/",
        supervisor_attendance_toggle_student,
        name="supervisor_attendance_toggle_student",
    ),
    path(
        "supervisor/attendance/workflow-action/",
        supervisor_workflow_roll_action,
        name="supervisor_workflow_roll_action",
    ),
    path(
        "supervisor/courses/quick-create/",
        supervisor_quick_course_create,
        name="supervisor_quick_course_create",
    ),
    path(
        "supervisor/students/drawer/",
        supervisor_student_drawer,
        name="supervisor_student_drawer",
    ),
    path("it/", it_portal, name="portal_it"),
    path("it/panels/diagnostics/", it_diagnostics_panel, name="it_diagnostics_panel"),
    path("it/panels/accounts/", it_accounts_panel, name="it_accounts_panel"),
    path("it/panels/support/", it_support_panel, name="it_support_panel"),
    path("it/workflows/notes/kpi/", it_notes_kpi, name="it_notes_kpi"),
    path("it/workflows/notes/section/", it_workflow_section, name="it_workflow_section"),
    path("it/workflows/notes/decisions/", it_notes_decisions, name="it_notes_decisions"),
    path("it/workflows/notes/", it_notes_flow_workspace, name="it_notes_flow_workspace"),
    path("workflows/reenrollment/", reenrollment_workspace, name="reenrollment_workspace"),
    path("workflows/reenrollment/propose/", reenrollment_propose, name="reenrollment_propose"),
    path("workflows/reenrollment/action/", reenrollment_decision_action, name="reenrollment_decision_action"),
    path("it/workflows/home/", it_home_workspace, name="it_home_workspace"),
    path("it/workflows/notes/action/", it_notes_workflow_action, name="it_notes_workflow_action"),
    path("it/workflows/notes/retake-modal/", it_notes_retake_modal, name="it_notes_retake_modal"),
    path("it/workflows/notes/load/", load_notes_workspace, name="load_notes_workspace"),
    path("it/workflows/accounts/", it_accounts_flow_workspace, name="it_accounts_flow_workspace"),
    path("it/workflows/accounts/action/", it_accounts_flow_action, name="it_accounts_flow_action"),
    path("it/workflows/accounts/users/<int:user_id>/", it_user_modal, name="it_user_modal"),
    path("it/workflows/accounts/users/<int:user_id>/save/", it_user_modal_save, name="it_user_modal_save"),
    path("it/workflows/support/", it_support_flow_workspace, name="it_support_flow_workspace"),
    path("it/workflows/support/action/", it_support_flow_action, name="it_support_flow_action"),
    path("it/workflows/audit/", it_audit_workspace, name="it_audit_workspace"),
    path("it/workflows/archives/", it_archives_workspace, name="it_archives_workspace"),
    path("it/workflows/archives/action/", it_archives_action, name="it_archives_action"),
    path("it/workflows/archives/<int:batch_id>/", it_archive_detail, name="it_archive_detail"),
    path("it/workflows/import/", it_import_workspace, name="it_import_workspace"),
    path("it/workflows/import/upload/", it_import_upload, name="it_import_upload"),
    path("it/workflows/import/export-notes/", it_export_notes_excel, name="it_export_notes_excel"),
    path("it/workflows/structure/", it_structure_workspace, name="it_structure_workspace"),
    path("it/workflows/structure/drawer/", it_structure_drawer, name="it_structure_drawer"),
    path("it/workflows/structure/modal/", it_structure_modal, name="it_structure_modal"),
    path("it/workflows/structure/action/", it_structure_action, name="it_structure_action"),
    path("it/workflows/supervision/", it_supervision_workspace, name="it_supervision_workspace"),
    path("it/workflows/catalog/", it_catalog_workspace, name="it_catalog_workspace"),
    path("it/workflows/catalog/action/", it_catalog_action, name="it_catalog_action"),
    path("it/workflows/cards/", it_cards_workspace, name="it_cards_workspace"),
    path("it/workflows/cards/class/pdf/", it_class_cards_pdf, name="it_class_cards_pdf"),
    path("it/workflows/cards/<int:student_id>/pdf/", it_student_card_pdf, name="it_student_card_pdf"),
    path("it/workflows/notifications/", it_notifications_workspace, name="it_notifications_workspace"),
    path("it/workflows/notifications/action/", it_notifications_action, name="it_notifications_action"),
    path("it/workflows/settings/", it_branch_settings_workspace, name="it_branch_settings_workspace"),
    path("it/workflows/settings/save/", it_branch_settings_save, name="it_branch_settings_save"),
    path("it/workflows/me/", it_my_account_workspace, name="it_my_account_workspace"),
    path("it/workflows/me/save/", it_my_account_save, name="it_my_account_save"),
    path("it/surveillance/workspace/", it_surveillance_workspace_view, name="it_surveillance_workspace"),
    path(
        "it/surveillance/student-followup/<int:student_id>/",
        it_surveillance_student_followup_view,
        name="it_surveillance_student_followup",
    ),
    path("surveillance/general/", surveillance_general_api_view, name="surveillance_general_api"),
    path("it/actions/toggle-account/", it_toggle_account, name="it_toggle_account"),
    path("it/actions/reset-password/", it_reset_password, name="it_reset_password"),
    path("it/actions/suspend-account/", it_suspend_account, name="it_suspend_account"),
    path("it/actions/reactivate-account/", it_reactivate_account, name="it_reactivate_account"),
    path("it/actions/unblock-account/", it_unblock_account, name="it_unblock_account"),
    path("it/actions/update-email/", it_update_account_email, name="it_update_account_email"),
    path("it/actions/tickets/create/", it_create_ticket, name="it_create_ticket"),
    path("it/actions/tickets/<int:ticket_id>/assign/", it_assign_ticket, name="it_assign_ticket"),
    path("it/actions/tickets/<int:ticket_id>/status/", it_update_ticket_status, name="it_update_ticket_status"),
    path("it/actions/tickets/<int:ticket_id>/comment/", it_comment_ticket, name="it_comment_ticket"),
    path(
        "supervisor/actions/student-attendance/",
        supervisor_mark_student_attendance,
        name="supervisor_mark_student_attendance",
    ),
    path(
        "supervisor/actions/teacher-attendance/",
        supervisor_mark_teacher_attendance,
        name="supervisor_mark_teacher_attendance",
    ),
    path(
        "supervisor/actions/lesson-log/",
        supervisor_save_lesson_log,
        name="supervisor_save_lesson_log",
    ),
    path(
        "supervisor/cases/",
        supervisor_cases_workspace,
        name="supervisor_cases_workspace",
    ),
    path(
        "supervisor/cases/create/",
        supervisor_case_create,
        name="supervisor_case_create",
    ),
    path(
        "supervisor/cases/<str:kind>/<int:case_id>/",
        supervisor_case_detail,
        name="supervisor_case_detail",
    ),
    path(
        "supervisor/cases/<str:kind>/<int:case_id>/advance/",
        supervisor_case_advance,
        name="supervisor_case_advance",
    ),
    path(
        "supervisor/cases/<str:kind>/<int:case_id>/notes/",
        supervisor_case_add_note,
        name="supervisor_case_add_note",
    ),
    path(
        "supervisor/students/<int:student_id>/cases/",
        supervisor_student_cases,
        name="supervisor_student_cases",
    ),
    path(
        "supervisor/teachers/drawer/",
        supervisor_teacher_drawer,
        name="supervisor_teacher_drawer",
    ),
    path(
        "supervisor/teachers/toggle-presence/",
        supervisor_toggle_teacher_presence,
        name="supervisor_toggle_teacher_presence",
    ),
    path(
        "supervisor/teachers/assign-replacement/",
        supervisor_assign_replacement,
        name="supervisor_assign_replacement",
    ),
    path(
        "supervisor/teachers/signal-incident/",
        supervisor_signal_teacher_incident,
        name="supervisor_signal_teacher_incident",
    ),
    path(
        "supervisor/convocation/drawer/",
        supervisor_convocation_drawer,
        name="supervisor_convocation_drawer",
    ),
    path(
        "supervisor/convocation/create/",
        supervisor_convocation_create,
        name="supervisor_convocation_create",
    ),
    path("admin/grades/", admin_grade_dashboard, name="admin_grade_dashboard"),
    path("it/grades/grid/", it_notes_grid_view, name="it_notes_grid"),
    path("it/grades/workspace/", it_notes_workspace_view, name="it_notes_workspace"),
    path("it/grades/pdf/<int:class_id>/<int:semester_id>/", class_grade_sheet_pdf_view, name="it_grade_sheet_pdf"),
    path("it/grades/print/<int:class_id>/<int:semester_id>/", class_grade_sheet_print_view, name="it_grade_sheet_print"),
    path("admin/grades/<int:enrollment_id>/", load_student_results, name="load_student_results"),
    path("admin/grades/<int:enrollment_id>/<int:semester_id>/", load_grades_table, name="load_grades_table"),
    path("admin/grades/save/", save_grade, name="save_grade"),
    path("admin/grades/save/confirm-otp/", save_grade_confirm_otp, name="save_grade_confirm_otp"),
    path(
        "admin/grades/<int:enrollment_id>/<int:semester_id>/publish/",
        publish_semester_view,
        name="publish_semester",
    ),
    path(
        "admin/grades/excel/<int:enrollment_id>/<int:semester_id>/",
        excel_grade_view,
        name="excel_grade_view",
    ),
    path(
        "it/grades/import/",
        it_grades_import_view,
        name="it_grades_import",
    ),
]
