from django.urls import path

from portal.views import (
    admin_grade_dashboard,
    it_notes_grid_view,
    it_notes_workspace_view,
    load_grades_table,
    load_student_results,
    publish_semester_view,
    save_grade,
)
from portal.views.admin_grades import excel_grade_view
from portal.views.it_grades_import import it_grades_import_view
from portal.views.it_surveillance import (
    it_surveillance_student_followup_view,
    it_surveillance_workspace_view,
    surveillance_general_api_view,
)
from portal.views.it_workflows import (
    it_accounts_flow_workspace,
    it_accounts_flow_action,
    it_audit_workspace,
    it_branch_settings_workspace,
    it_branch_settings_save,
    it_cards_workspace,
    it_class_cards_pdf,
    it_catalog_action,
    it_catalog_workspace,
    it_export_notes_excel,
    it_home_workspace,
    it_import_upload,
    it_import_workspace,
    it_my_account_workspace,
    it_my_account_save,
    it_notes_flow_workspace,
    it_notes_workflow_action,
    it_structure_workspace,
    it_student_card_pdf,
    it_supervision_workspace,
    it_support_flow_action,
    it_support_flow_workspace,
    it_user_modal,
    it_user_modal_save,
    load_notes_workspace,
)
from portal.views.views import (
    admissions_portal,
    dg_portal,
    director_portal,
    finance_portal,
    it_accounts_panel,
    it_assign_ticket,
    it_comment_ticket,
    it_create_ticket,
    it_diagnostics_panel,
    it_portal,
    it_reactivate_account,
    it_reset_password,
    it_support_panel,
    it_suspend_account,
    it_toggle_account,
    it_unblock_account,
    it_update_account_email,
    it_update_ticket_status,
    portal_dashboard,
    portal_home,
    secretary_portal,
    staff_portal,
    student_portal,
    supervisor_attendance_roll_action,
    supervisor_attendance_workflow_refresh,
    supervisor_bulk_attendance_roster,
    supervisor_bulk_attendance_save,
    supervisor_mark_student_attendance,
    supervisor_mark_teacher_attendance,
    supervisor_planner_hub,
    supervisor_planner_view_workspace,
    supervisor_planner_workspace,
    supervisor_portal,
    supervisor_class_detail,
    supervisor_create_schedule_event,
    supervisor_student_options,
    supervisor_quick_search,
    supervisor_quick_course_create,
    supervisor_save_lesson_log,
    supervisor_session_close,
    supervisor_session_start,
    supervisor_student_drawer,
    supervisor_weekly_slot_save,
    supervisor_weekly_slots_workspace,
    supervisor_workflow_roll_action,
    supervisor_workflow_workspace,
    supervisor_attendance_toggle_student,
    teacher_portal,
)

app_name = "accounts_portal"

urlpatterns = [
    path("", portal_home, name="portal_home"),
    path("dashboard/", portal_dashboard, name="portal_dashboard"),
    path("student/", student_portal, name="portal_student"),
    path("staff/", staff_portal, name="portal_staff"),
    path("teacher/", teacher_portal, name="portal_teacher"),
    path("finance/", finance_portal, name="portal_finance"),
    path("secretary/", secretary_portal, name="portal_secretary"),
    path("admissions/", admissions_portal, name="portal_admissions"),
    path("director/", director_portal, name="portal_director"),
    path("dg/", dg_portal, name="portal_dg"),
    path("supervisor/", supervisor_portal, name="portal_supervisor"),
    path("supervisor/search/", supervisor_quick_search, name="supervisor_quick_search"),
    path(
        "supervisor/classes/<int:class_id>/",
        supervisor_class_detail,
        name="supervisor_class_detail",
    ),
    path(
        "supervisor/planner/hub/",
        supervisor_planner_hub,
        name="supervisor_planner_hub",
    ),
    path(
        "supervisor/planner/view/",
        supervisor_planner_view_workspace,
        name="supervisor_planner_view_workspace",
    ),
    path(
        "supervisor/planner/workspace/",
        supervisor_planner_workspace,
        name="supervisor_planner_workspace",
    ),
    path(
        "supervisor/classes/<int:class_id>/schedule/create/",
        supervisor_create_schedule_event,
        name="supervisor_create_schedule_event",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/save/",
        supervisor_weekly_slot_save,
        name="supervisor_weekly_slot_save",
    ),
    path(
        "supervisor/classes/<int:class_id>/weekly-slots/",
        supervisor_weekly_slots_workspace,
        name="supervisor_weekly_slots_workspace",
    ),
    path(
        "supervisor/student-options/",
        supervisor_student_options,
        name="supervisor_student_options",
    ),
    path(
        "supervisor/workspace/",
        supervisor_workflow_workspace,
        name="supervisor_workflow_workspace",
    ),
    path(
        "supervisor/attendance/toggle/",
        supervisor_attendance_toggle_student,
        name="supervisor_attendance_toggle_student",
    ),
    path(
        "supervisor/attendance/workflow-action/",
        supervisor_workflow_roll_action,
        name="supervisor_workflow_roll_action",
    ),
    path(
        "supervisor/courses/quick-create/",
        supervisor_quick_course_create,
        name="supervisor_quick_course_create",
    ),
    path(
        "supervisor/students/drawer/",
        supervisor_student_drawer,
        name="supervisor_student_drawer",
    ),
    path("it/", it_portal, name="portal_it"),
    path("it/panels/diagnostics/", it_diagnostics_panel, name="it_diagnostics_panel"),
    path("it/panels/accounts/", it_accounts_panel, name="it_accounts_panel"),
    path("it/panels/support/", it_support_panel, name="it_support_panel"),
    path("it/workflows/notes/", it_notes_flow_workspace, name="it_notes_flow_workspace"),
    path("it/workflows/home/", it_home_workspace, name="it_home_workspace"),
    path("it/workflows/notes/action/", it_notes_workflow_action, name="it_notes_workflow_action"),
    path("it/workflows/notes/load/", load_notes_workspace, name="load_notes_workspace"),
    path("it/workflows/accounts/", it_accounts_flow_workspace, name="it_accounts_flow_workspace"),
    path("it/workflows/accounts/action/", it_accounts_flow_action, name="it_accounts_flow_action"),
    path("it/workflows/accounts/users/<int:user_id>/", it_user_modal, name="it_user_modal"),
    path("it/workflows/accounts/users/<int:user_id>/save/", it_user_modal_save, name="it_user_modal_save"),
    path("it/workflows/support/", it_support_flow_workspace, name="it_support_flow_workspace"),
    path("it/workflows/support/action/", it_support_flow_action, name="it_support_flow_action"),
    path("it/workflows/audit/", it_audit_workspace, name="it_audit_workspace"),
    path("it/workflows/import/", it_import_workspace, name="it_import_workspace"),
    path("it/workflows/import/upload/", it_import_upload, name="it_import_upload"),
    path("it/workflows/import/export-notes/", it_export_notes_excel, name="it_export_notes_excel"),
    path("it/workflows/structure/", it_structure_workspace, name="it_structure_workspace"),
    path("it/workflows/supervision/", it_supervision_workspace, name="it_supervision_workspace"),
    path("it/workflows/catalog/", it_catalog_workspace, name="it_catalog_workspace"),
    path("it/workflows/catalog/action/", it_catalog_action, name="it_catalog_action"),
    path("it/workflows/cards/", it_cards_workspace, name="it_cards_workspace"),
    path("it/workflows/cards/class/pdf/", it_class_cards_pdf, name="it_class_cards_pdf"),
    path("it/workflows/cards/<int:student_id>/pdf/", it_student_card_pdf, name="it_student_card_pdf"),
    path("it/workflows/settings/", it_branch_settings_workspace, name="it_branch_settings_workspace"),
    path("it/workflows/settings/save/", it_branch_settings_save, name="it_branch_settings_save"),
    path("it/workflows/me/", it_my_account_workspace, name="it_my_account_workspace"),
    path("it/workflows/me/save/", it_my_account_save, name="it_my_account_save"),
    path("it/surveillance/workspace/", it_surveillance_workspace_view, name="it_surveillance_workspace"),
    path(
        "it/surveillance/student-followup/<int:student_id>/",
        it_surveillance_student_followup_view,
        name="it_surveillance_student_followup",
    ),
    path("surveillance/general/", surveillance_general_api_view, name="surveillance_general_api"),
    path("it/actions/toggle-account/", it_toggle_account, name="it_toggle_account"),
    path("it/actions/reset-password/", it_reset_password, name="it_reset_password"),
    path("it/actions/suspend-account/", it_suspend_account, name="it_suspend_account"),
    path("it/actions/reactivate-account/", it_reactivate_account, name="it_reactivate_account"),
    path("it/actions/unblock-account/", it_unblock_account, name="it_unblock_account"),
    path("it/actions/update-email/", it_update_account_email, name="it_update_account_email"),
    path("it/actions/tickets/create/", it_create_ticket, name="it_create_ticket"),
    path("it/actions/tickets/<int:ticket_id>/assign/", it_assign_ticket, name="it_assign_ticket"),
    path("it/actions/tickets/<int:ticket_id>/status/", it_update_ticket_status, name="it_update_ticket_status"),
    path("it/actions/tickets/<int:ticket_id>/comment/", it_comment_ticket, name="it_comment_ticket"),
    path(
        "supervisor/actions/student-attendance/",
        supervisor_mark_student_attendance,
        name="supervisor_mark_student_attendance",
    ),
    path(
        "supervisor/actions/teacher-attendance/",
        supervisor_mark_teacher_attendance,
        name="supervisor_mark_teacher_attendance",
    ),
    path(
        "supervisor/actions/lesson-log/",
        supervisor_save_lesson_log,
        name="supervisor_save_lesson_log",
    ),
    path(
        "supervisor/actions/session/start/",
        supervisor_session_start,
        name="supervisor_session_start",
    ),
    path(
        "supervisor/actions/session/close/",
        supervisor_session_close,
        name="supervisor_session_close",
    ),
    path(
        "supervisor/bulk-attendance/roster/",
        supervisor_bulk_attendance_roster,
        name="supervisor_bulk_attendance_roster",
    ),
    path(
        "supervisor/bulk-attendance/save/",
        supervisor_bulk_attendance_save,
        name="supervisor_bulk_attendance_save",
    ),
    path(
        "supervisor/attendance/workflow/",
        supervisor_attendance_workflow_refresh,
        name="supervisor_attendance_workflow_refresh",
    ),
    path(
        "supervisor/attendance/roll-action/",
        supervisor_attendance_roll_action,
        name="supervisor_attendance_roll_action",
    ),
    path("admin/grades/", admin_grade_dashboard, name="admin_grade_dashboard"),
    path("it/grades/grid/", it_notes_grid_view, name="it_notes_grid"),
    path("it/grades/workspace/", it_notes_workspace_view, name="it_notes_workspace"),
    path("admin/grades/<int:enrollment_id>/", load_student_results, name="load_student_results"),
    path("admin/grades/<int:enrollment_id>/<int:semester_id>/", load_grades_table, name="load_grades_table"),
    path("admin/grades/save/", save_grade, name="save_grade"),
    path(
        "admin/grades/<int:enrollment_id>/<int:semester_id>/publish/",
        publish_semester_view,
        name="publish_semester",
    ),
    path(
        "admin/grades/excel/<int:enrollment_id>/<int:semester_id>/",
        excel_grade_view,
        name="excel_grade_view",
    ),
    path(
        "it/grades/import/",
        it_grades_import_view,
        name="it_grades_import",
    ),
]
