from django.urls import path
from .views import (
    courses_partial,
    ec_detail,
    dashboard,
    profile_partial,
    academics_partial,
    finance_partial,
    settings_partial,
    messages_partial,
    notifications_partial,
    student_courses,
    timetable_partial,
    shop_orders_partial,
    shop_catalog_partial,
    shop_cart_partial,
    update_settings_profile,
    update_settings_account,
    update_settings_preferences,
    update_settings_password,
    upload_settings_document,
    update_content_progress,
    ec_preview,
    mark_message_read,
    mark_all_messages_read,
    mark_message_unread,
)

app_name = "portal_student"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile/", profile_partial, name="profile_partial"),
    path("academics/", academics_partial, name="academics_partial"),
    path("finance/", finance_partial, name="finance_partial"),
    path("settings/", settings_partial, name="settings_partial"),
    path("notifications/", notifications_partial, name="notifications_partial"),
    path("partials/courses/", courses_partial, name="courses_partial"),
    path("partials/messages/", messages_partial, name="messages_partial"),
    path("partials/messages/read-all/", mark_all_messages_read, name="mark_all_messages_read"),
    path("partials/messages/<int:message_id>/read/", mark_message_read, name="mark_message_read"),
    path("partials/messages/<int:message_id>/unread/", mark_message_unread, name="mark_message_unread"),
    path("partials/timetable/", timetable_partial, name="timetable_partial"),
    path("partials/shop-orders/", shop_orders_partial, name="shop_orders_partial"),
    path("partials/shop-catalog/", shop_catalog_partial, name="shop_catalog_partial"),
    path("partials/shop-cart/", shop_cart_partial, name="shop_cart_partial"),
    path("courses/", student_courses, name="student_courses"),
    path("courses/ec/<int:ec_id>/", ec_detail, name="ec_detail"),
    path("courses/ec/<int:ec_id>/preview/", ec_preview, name="ec_preview"),
    path("contents/<int:content_id>/progress/", update_content_progress, name="content_progress"),
    path("settings/profile/", update_settings_profile, name="update_settings_profile"),
    path("settings/account/", update_settings_account, name="update_settings_account"),
    path("settings/preferences/", update_settings_preferences, name="update_settings_preferences"),
    path("settings/password/", update_settings_password, name="update_settings_password"),
    path("settings/documents/", upload_settings_document, name="upload_settings_document"),
]
