# Generated by Django 6.0.1 on 2026-04-22 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_image'),
        ('formations', '0008_delete_programavailability'),
        ('inscriptions', '0005_alter_statushistory_options_inscription_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Format : 2025-2026', max_length=9, unique=True)),
                ('start_date', models.DateField(help_text="Date de début de l'année académique")),
                ('end_date', models.DateField(help_text="Date de fin de l'année académique")),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Une seule année doit être active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_enrollments', to='branches.branch')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_enrollment', to='inscriptions.inscription')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_enrollments', to='formations.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_enrollments', to=settings.AUTH_USER_MODEL)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_enrollments', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Inscription académique',
                'verbose_name_plural': 'Inscriptions académiques',
            },
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('study_level', models.CharField(blank=True, choices=[('DEF', "Diplôme d'Études Fondamentales"), ('BAC', 'Baccalauréat'), ('LICENCE', 'Licence'), ('MASTER', 'Master')], max_length=20, null=True)),
                ('validation_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_classes', to='branches.branch')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_classes', to='formations.programme')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_classes', to='academics.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_required_credits', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicclass')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credit_required', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs', to='academics.ue')),
            ],
        ),
        migrations.CreateModel(
            name='ECGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note_coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credit_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.ec')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_grades', to='academics.academicenrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'ec')},
            },
        ),
    ]
