# Generated by Django 6.0.1 on 2026-04-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicenrollment',
            name='academic_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicclass'),
            preserve_default=False,
        ),
    ]
