# Generated by Django 6.0.1 on 2026-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicenrollment_academic_class'),
        ('branches', '0002_branch_image'),
        ('formations', '0008_delete_programavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicclass',
            options={'ordering': ['programme__title', 'branch__name', 'level'], 'verbose_name': 'Classe académique', 'verbose_name_plural': 'Classes académiques'},
        ),
        migrations.AlterModelOptions(
            name='academicenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription académique', 'verbose_name_plural': 'Inscriptions académiques'},
        ),
        migrations.AlterModelOptions(
            name='ec',
            options={'ordering': ['ue', 'id'], 'verbose_name': 'EC', 'verbose_name_plural': 'EC'},
        ),
        migrations.AlterModelOptions(
            name='ecgrade',
            options={'ordering': ['enrollment', 'ec'], 'verbose_name': 'Note EC', 'verbose_name_plural': 'Notes EC'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['academic_class', 'number'], 'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['semester', 'code'], 'verbose_name': 'UE', 'verbose_name_plural': 'UE'},
        ),
        migrations.AlterUniqueTogether(
            name='ecgrade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='level',
            field=models.CharField(help_text='Exemples : L1, L2, L3, M1, M2...', max_length=10),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='name',
            field=models.CharField(blank=True, help_text="Nom libre temporaire. Peut rester vide si l'affichage est reconstruit dynamiquement.", max_length=100),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='study_level',
            field=models.CharField(blank=True, choices=[('DEF', "Diplôme d'Études Fondamentales"), ('BAC', 'Baccalauréat'), ('LICENCE', 'Licence'), ('MASTER', 'Master')], help_text="Niveau d'études d'entrée ou de référence pour la logique métier.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='validation_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seuil de validation de référence : 10 ou 12 selon le niveau.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Une seule année académique doit être active à la fois.'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='Format attendu : 2025-2026', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')]),
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('programme', 'branch', 'academic_year', 'level'), name='unique_academic_class_per_programme_branch_year_level'),
        ),
        migrations.AddConstraint(
            model_name='ecgrade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'ec'), name='unique_ec_grade_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('academic_class', 'number'), name='unique_semester_per_academic_class'),
        ),
        migrations.AddConstraint(
            model_name='ue',
            constraint=models.UniqueConstraint(fields=('semester', 'code'), name='unique_ue_code_per_semester'),
        ),
    ]
