# Generated by Django 6.0.1 on 2026-04-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicclass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgrade',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
