# Generated by Django 6.0.1 on 2026-04-26 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_ecchapter_restructure_eccontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eccontent',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eccontent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='eccontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eccontent',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('doc', 'Word'), ('excel', 'Excel'), ('ppt', 'PowerPoint'), ('image', 'Image'), ('audio', 'Audio'), ('text', 'Texte')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_position', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='academics.eccontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression contenu etudiant',
                'verbose_name_plural': 'Progressions contenus etudiants',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'content'), name='unique_student_content_progress')],
            },
        ),
    ]
