# Generated by Django 6.0.1 on 2026-04-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_eccontent_duration_eccontent_is_active_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('course', 'Cours'), ('exam', 'Examen'), ('meeting', 'Reunion'), ('practical', 'Travaux pratiques'), ('seminar', 'Seminaire'), ('other', 'Autre')], db_index=True, default='course', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('planned', 'Planifie'), ('ongoing', 'En cours'), ('completed', 'Termine'), ('postponed', 'Reporte'), ('cancelled', 'Annule')], db_index=True, default='draft', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_schedule_events', to=settings.AUTH_USER_MODEL)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='academics.ec')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_schedule_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_schedule_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement academique',
                'verbose_name_plural': 'Evenements academiques',
                'ordering': ['start_datetime', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Cree'), ('updated', 'Mis a jour'), ('postponed', 'Reporte'), ('cancelled', 'Annule'), ('completed', 'Termine')], db_index=True, max_length=20)),
                ('old_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('old_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_change_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='academics.academicscheduleevent')),
            ],
            options={
                'verbose_name': 'Historique emploi du temps',
                'verbose_name_plural': 'Historiques emploi du temps',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicScheduleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_schedule_events', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_schedule_execution_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='academics.academicscheduleevent')),
            ],
            options={
                'verbose_name': 'Execution emploi du temps',
                'verbose_name_plural': 'Executions emploi du temps',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='academicscheduleevent',
            index=models.Index(fields=['branch', 'academic_year', 'start_datetime'], name='academics_a_branch__cff706_idx'),
        ),
        migrations.AddIndex(
            model_name='academicscheduleevent',
            index=models.Index(fields=['academic_class', 'start_datetime'], name='academics_a_academi_9102f8_idx'),
        ),
        migrations.AddIndex(
            model_name='academicscheduleevent',
            index=models.Index(fields=['teacher', 'start_datetime'], name='academics_a_teacher_41fa23_idx'),
        ),
        migrations.AddIndex(
            model_name='academicscheduleevent',
            index=models.Index(fields=['status', 'start_datetime'], name='academics_a_status_8e4677_idx'),
        ),
    ]
