# Generated by Django 6.0.1 on 2026-04-28 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_academicscheduleevent_academicschedulechangelog_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPresenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_count', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_checks', to='academics.academicclass')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_checks', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_presence_checks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_checks', to='academics.academicscheduleevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'created_at'], name='academics_c_branch__e2e6f6_idx'), models.Index(fields=['academic_class', 'created_at'], name='academics_c_academi_8ce8c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('absence', 'Absence'), ('late', 'Retard'), ('discipline', 'Discipline'), ('visit', 'Visite de classe'), ('observation', 'Observation'), ('escalation', 'Remontee')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En suivi'), ('resolved', 'Resolue')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_notes', to='academics.academicclass')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveillance_notes', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_surveillance_notes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_notes', to='academics.academicscheduleevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_surveillance_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_notes_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_notes_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'status', 'severity'], name='academics_s_branch__888c03_idx'), models.Index(fields=['branch', 'note_type', 'created_at'], name='academics_s_branch__bae411_idx'), models.Index(fields=['academic_class', 'status'], name='academics_s_academi_00bf4a_idx')],
            },
        ),
    ]
