# Generated by Django 6.0.1 on 2026-04-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_academicscheduleevent_academicschedulechangelog_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('planned', 'Planifie'), ('done', 'Fait'), ('cancelled', 'Annule'), ('absent_teacher', 'Enseignant absent')], db_index=True, default='planned', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_logs', to='academics.academicclass')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_logs', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lesson_logs', to=settings.AUTH_USER_MODEL)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_logs', to='academics.ec')),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_logs', to='academics.academicscheduleevent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_logs', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_lesson_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cahier de texte',
                'verbose_name_plural': 'Cahiers de texte',
                'ordering': ['-date', '-start_time', '-id'],
                'indexes': [models.Index(fields=['academic_class', 'date'], name='academics_l_academi_d8120b_idx'), models.Index(fields=['teacher', 'date'], name='academics_l_teacher_a8ad65_idx'), models.Index(fields=['branch', 'date'], name='academics_l_branch__f8b977_idx'), models.Index(fields=['status', 'date'], name='academics_l_status_227fc9_idx')],
            },
        ),
    ]
