# Generated by Django 6.0.1 on 2026-04-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_classpresencecheck_surveillancenote'),
        ('academics', '0012_lessonlog'),
    ]

    operations = [
    ]
