# Generated by Django 6.0.1 on 2026-05-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_merge_20260430_0744'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classpresencecheck',
            name='academics_c_branch__e2e6f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='classpresencecheck',
            name='academics_c_academi_8ce8c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveillancenote',
            name='academics_s_branch__888c03_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveillancenote',
            name='academics_s_branch__bae411_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveillancenote',
            name='academics_s_academi_00bf4a_idx',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='event',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='student',
        ),
        migrations.RemoveField(
            model_name='surveillancenote',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ClassPresenceCheck',
        ),
        migrations.DeleteModel(
            name='SurveillanceNote',
        ),
    ]
