# Generated by Django 5.2.5 on 2026-05-02 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_classpresencecheck_academics_c_branch__e2e6f6_idx_and_more'),
        ('branches', '0002_branch_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_slots', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedule_slots', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedule_slots', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_weekly_schedule_slots', to=settings.AUTH_USER_MODEL)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedule_slots', to='academics.ec')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_teaching_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creneau hebdomadaire',
                'verbose_name_plural': 'Creneaux hebdomadaires',
                'ordering': ['weekday', 'start_time', 'id'],
                'indexes': [models.Index(fields=['branch', 'academic_year', 'weekday'], name='academics_w_branch__92b222_idx'), models.Index(fields=['academic_class', 'is_active'], name='academics_w_academi_184f53_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_class', 'weekday', 'start_time'), name='unique_weekly_slot_start_per_class_day')],
            },
        ),
    ]
