# Generated by Django 6.0.5 on 2026-05-17 23:24

from django.db import migrations, models


def backfill_academic_enrollment_status(apps, schema_editor):
    AcademicEnrollment = apps.get_model("academics", "AcademicEnrollment")
    AcademicEnrollment.objects.filter(is_archived=True).update(status="ARCHIVED", is_active=False)
    AcademicEnrollment.objects.filter(is_archived=False, is_active=False).update(status="ARCHIVED")
    AcademicEnrollment.objects.filter(is_archived=False, is_active=True).update(status="ACTIVE")


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_academic_archive_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivee'), ('COMPLETED', 'Terminee'), ('SUSPENDED', 'Suspendue'), ('TRANSFERRED', 'Transferee'), ('ABANDONED', 'Abandonnee')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.RunPython(backfill_academic_enrollment_status, migrations.RunPython.noop),
    ]
