# Generated by Django 6.0.5 on 2026-05-25 12:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_academicenrollment_status'),
        ('branches', '0002_branch_image'),
        ('formations', '0008_delete_programavailability'),
        ('students', '0011_studentyeardecision_decision_payload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_type', models.CharField(choices=[('semester', 'Bulletin semestriel'), ('annual', 'Bulletin annuel')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Genere'), ('published', 'Publie'), ('cancelled', 'Annule')], db_index=True, default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60, unique=True)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('credits_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('decision', models.CharField(blank=True, db_index=True, max_length=80)),
                ('mention', models.CharField(blank=True, max_length=80)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='academics/bulletins/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_bulletins', to='branches.branch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='academics.academicenrollment')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_academic_bulletins', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_academic_bulletins', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_bulletins', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'academic_year', 'status'], name='academics_a_branch__cc7468_idx'), models.Index(fields=['academic_class', 'bulletin_type', 'status'], name='academics_a_academi_a0e0da_idx'), models.Index(fields=['student', 'academic_year'], name='academics_a_student_606fb1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('bulletin_type', 'semester')), fields=('student', 'enrollment', 'bulletin_type', 'semester'), name='academics_unique_semester_bulletin'), models.UniqueConstraint(condition=models.Q(('bulletin_type', 'annual')), fields=('student', 'enrollment', 'bulletin_type'), name='academics_unique_annual_bulletin')],
            },
        ),
        migrations.CreateModel(
            name='AcademicDiplomaAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Pret'), ('delivered', 'Delivre'), ('cancelled', 'Annule')], db_index=True, default='draft', max_length=20)),
                ('final_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, max_length=80)),
                ('decision', models.CharField(blank=True, db_index=True, max_length=80)),
                ('awarded_at', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='academics/diplomas/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diploma_awards', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diploma_awards', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_diploma_awards', to='branches.branch')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_academic_diplomas', to=settings.AUTH_USER_MODEL)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_awards', to='formations.diploma')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diploma_awards', to='academics.academicenrollment')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_academic_diplomas', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_diploma_awards', to='formations.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_diploma_awards', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'academic_year', 'status'], name='academics_a_branch__7aad5b_idx'), models.Index(fields=['student', 'status'], name='academics_a_student_986823_idx'), models.Index(fields=['programme', 'status'], name='academics_a_program_52cd98_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'programme', 'academic_year'), name='academics_unique_diploma_award_student_programme_year')],
            },
        ),
    ]
