# Generated by Django 6.0.5 on 2026-06-04 18:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_academicbulletin_academicdiplomaaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='admissibility_gap',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text="Marge d'admissibilité en points sous le seuil. Ex: 2 = admissible si moyenne ≥ seuil - 2.", max_digits=4),
        ),
    ]
