# Generated by Django 6.0.5 on 2026-06-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_add_admissibility_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_original', models.DecimalField(decimal_places=2, help_text='Note originale ayant cause la dette.', max_digits=5)),
                ('score_retake', models.DecimalField(blank=True, decimal_places=2, help_text="Note de repêchage (mise a jour quand l'EC est repasse).", max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('cleared', 'Soldee')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='academics.academicyear')),
                ('carry_forward_to', models.ForeignKey(blank=True, help_text='Annee academique vers laquelle la dette est reportee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_debts', to='academics.academicyear')),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='academics.ec')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='academics.academicenrollment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Dette academique',
                'verbose_name_plural': 'Dettes academiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='academics_a_enrollm_e88b89_idx'), models.Index(fields=['ec', 'status'], name='academics_a_ec_id_357188_idx'), models.Index(fields=['academic_year', 'status'], name='academics_a_academi_0963a3_idx'), models.Index(fields=['academic_class', 'status'], name='academics_a_academi_c1663a_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'ec', 'semester', 'academic_year'), name='academics_unique_debt_per_enrollment_ec_semester_year')],
            },
        ),
    ]
