# Generated by Django 6.0.5 on 2026-06-04 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_academicdebt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Seuil de validation utilise.', max_digits=4)),
                ('admissibility_gap', models.DecimalField(decimal_places=2, help_text="Marge d'admissibilite utilisee.", max_digits=4)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('validated_count', models.PositiveIntegerField(default=0)),
                ('admissible_count', models.PositiveIntegerField(default=0)),
                ('non_admis_count', models.PositiveIntegerField(default=0)),
                ('rule_codes_used', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='academics.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='academics.academicyear')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_decision_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de decision annuelle',
                'verbose_name_plural': 'Journaux de decisions annuelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
