# Generated by Django 6.0.5 on 2026-07-07 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_academic_decision_log'),
        ('branches', '0003_branch_cash_reserve_target'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendars', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_academic_calendars', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_academic_calendars', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_academic_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendrier academique',
                'verbose_name_plural': 'Calendriers academiques',
                'ordering': ['-academic_year__start_date', 'branch__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('academic_start', 'Rentree academique'), ('academic_end', 'Cloture academique'), ('semester_start', 'Debut de semestre'), ('semester_end', 'Fin de semestre'), ('holiday', 'Vacances'), ('public_holiday', 'Jour ferie'), ('registration', 'Inscription'), ('reregistration', 'Reinscription'), ('exam_session', "Session d'examens"), ('retake_session', 'Session de rattrapage'), ('jury', 'Jury'), ('result_publication', 'Publication des resultats'), ('ceremony', 'Ceremonie'), ('meeting', 'Reunion'), ('other', 'Autre')], db_index=True, max_length=30)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('all_day', models.BooleanField(default=False)),
                ('target_scope', models.CharField(choices=[('branch', 'Annexe'), ('programme', 'Programme'), ('class', 'Classe'), ('semester', 'Semestre')], db_index=True, default='branch', max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('is_blocking', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('cancelled', 'Annule'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_entries', to='academics.academicclass')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.academiccalendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_academic_calendar_entries', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_entries', to='formations.programme')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_entries', to='academics.semester')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_academic_calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entree du calendrier academique',
                'verbose_name_plural': 'Entrees du calendrier academique',
                'ordering': ['start_datetime', 'id'],
            },
        ),
        migrations.AddField(
            model_name='academicscheduleevent',
            name='calendar_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='academics.academiccalendarentry'),
        ),
        migrations.AddIndex(
            model_name='academiccalendar',
            index=models.Index(fields=['branch', 'academic_year', 'status'], name='academics_a_branch__383e10_idx'),
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.UniqueConstraint(fields=('branch', 'academic_year', 'version'), name='unique_calendar_version_per_branch_year'),
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('branch', 'academic_year'), name='unique_published_calendar_branch_year'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarentry',
            index=models.Index(fields=['calendar', 'start_datetime'], name='academics_a_calenda_35b911_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarentry',
            index=models.Index(fields=['event_type', 'start_datetime'], name='academics_a_event_t_8647ad_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarentry',
            index=models.Index(fields=['status', 'start_datetime'], name='academics_a_status_15fc57_idx'),
        ),
    ]
