# Generated by Django 6.0.5 on 2026-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_academiccalendar_validated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ec',
            name='structure_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('complete', 'Complet'), ('validated', 'Valide'), ('published', 'Publie'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='ue',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ue',
            name='structure_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('complete', 'Complet'), ('validated', 'Valide'), ('published', 'Publie'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20),
        ),
    ]
