# Generated by Django 6.0.5 on 2026-07-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_academiccalendarentry_supervisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendarentry',
            name='supervisors',
        ),
    ]
