# Generated by Django 6.0.5 on 2026-08-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_remove_academiccalendarentry_supervisors'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='administrative_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='general_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='official_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_academic_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='academics.academiccalendar'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_academic_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_academic_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis pour validation'), ('validated', 'Valide'), ('rejected', 'A corriger'), ('published', 'Publie'), ('superseded', 'Remplace'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicCalendarDisruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('administrative', 'Suspension administrative'), ('security', 'Situation securitaire'), ('strike', 'Greve ou mouvement social'), ('health', 'Situation sanitaire'), ('weather', 'Intemperie'), ('other', 'Autre perturbation')], max_length=30)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('target_scope', models.CharField(choices=[('branch', 'Annexe'), ('programme', 'Programme'), ('class', 'Classe'), ('semester', 'Semestre')], default='branch', max_length=20)),
                ('in_person_impact', models.CharField(choices=[('unknown', 'A preciser'), ('unaffected', 'Sans impact'), ('maintained', 'Maintenu'), ('partial', 'Partiellement maintenu'), ('suspended', 'Suspendu'), ('postponed', 'Reporte')], default='unknown', max_length=20)),
                ('online_impact', models.CharField(choices=[('unknown', 'A preciser'), ('unaffected', 'Sans impact'), ('maintained', 'Maintenu'), ('partial', 'Partiellement maintenu'), ('suspended', 'Suspendu'), ('postponed', 'Reporte')], default='unknown', max_length=20)),
                ('assessment_impact', models.CharField(choices=[('unknown', 'A preciser'), ('unaffected', 'Sans impact'), ('maintained', 'Maintenu'), ('partial', 'Partiellement maintenu'), ('suspended', 'Suspendu'), ('postponed', 'Reporte')], default='unknown', max_length=20)),
                ('internship_impact', models.CharField(choices=[('unknown', 'A preciser'), ('unaffected', 'Sans impact'), ('maintained', 'Maintenu'), ('partial', 'Partiellement maintenu'), ('suspended', 'Suspendu'), ('postponed', 'Reporte')], default='unknown', max_length=20)),
                ('supporting_document', models.FileField(blank=True, upload_to='academic_calendar/disruptions/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En cours'), ('closed', 'Cloturee'), ('cancelled', 'Annulee')], default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_disruptions', to='academics.academicclass')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disruptions', to='academics.academiccalendar')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_academic_calendar_disruptions', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_disruptions', to='formations.programme')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_academic_calendar_disruptions', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_disruptions', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Perturbation du calendrier academique',
                'verbose_name_plural': 'Perturbations du calendrier academique',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('maintain', 'Maintenir'), ('online_continuity', 'Continuite en ligne'), ('reschedule', 'Reporter / modifier les dates'), ('cancel', 'Annuler exceptionnellement')], max_length=30)),
                ('reason', models.TextField()),
                ('previous_start_datetime', models.DateTimeField()),
                ('previous_end_datetime', models.DateTimeField()),
                ('effective_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('effective_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('official_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis pour validation'), ('validated', 'Valide'), ('rejected', 'A corriger'), ('published', 'Publie'), ('cancelled', 'Annule')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='academics.academiccalendar')),
                ('calendar_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='academics.academiccalendarentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_academic_calendar_adjustments', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_academic_calendar_adjustments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_academic_calendar_adjustments', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_academic_calendar_adjustments', to=settings.AUTH_USER_MODEL)),
                ('disruption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='academics.academiccalendardisruption')),
            ],
            options={
                'verbose_name': 'Avenant au calendrier academique',
                'verbose_name_plural': 'Avenants au calendrier academique',
                'ordering': ['calendar_entry__start_datetime', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='academiccalendardisruption',
            index=models.Index(fields=['calendar', 'status', 'starts_at'], name='academics_a_calenda_40eb61_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendaradjustment',
            index=models.Index(fields=['calendar', 'status'], name='academics_a_calenda_ea585e_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendaradjustment',
            index=models.Index(fields=['calendar_entry', 'status'], name='academics_a_calenda_2de056_idx'),
        ),
    ]
