# Generated by Django 6.0.5 on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0028_academic_calendar_governance"),
        ("branches", "0003_branch_cash_reserve_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("normal", "Session normale"), ("retake", "Session de rattrapage")], db_index=True, max_length=12)),
                ("title", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("preparation", "Préparation"), ("subjects", "Collecte des sujets"), ("planned", "Planifiée"), ("in_progress", "En cours"), ("corrections", "Corrections"), ("review", "Contrôle des résultats"), ("results_published", "Résultats publiés"), ("closed", "Clôturée"), ("cancelled", "Annulée")], db_index=True, default="preparation", max_length=24)),
                ("exception_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_campaigns", to="academics.academicyear")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_campaigns", to="branches.branch")),
                ("calendar_entry", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_campaigns", to="academics.academiccalendarentry")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_evaluation_campaigns", to=settings.AUTH_USER_MODEL)),
                ("result_publication_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="result_publication_campaigns", to="academics.academiccalendarentry")),
                ("source_campaign", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retake_campaigns", to="academics.evaluationcampaign")),
            ],
            options={"ordering": ["calendar_entry__start_datetime", "id"]},
        ),
        migrations.AddField(
            model_name="academicscheduleevent",
            name="evaluation_campaign",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="schedule_events", to="academics.evaluationcampaign"),
        ),
        migrations.CreateModel(
            name="EvaluationCampaignScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("included", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("academic_class", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_campaign_scopes", to="academics.academicclass")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scopes", to="academics.evaluationcampaign")),
                ("semester", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_campaign_scopes", to="academics.semester")),
            ],
        ),
        migrations.AddIndex(model_name="evaluationcampaign", index=models.Index(fields=["branch", "academic_year", "status"], name="academics_e_branch__02e40e_idx")),
        migrations.AddIndex(model_name="evaluationcampaign", index=models.Index(fields=["calendar_entry", "kind"], name="academics_e_calenda_b5bb63_idx")),
        migrations.AddIndex(model_name="evaluationcampaignscope", index=models.Index(fields=["campaign", "included"], name="academics_e_campaig_ee00e6_idx")),
        migrations.AddConstraint(model_name="evaluationcampaignscope", constraint=models.UniqueConstraint(fields=("campaign", "academic_class", "semester"), name="academics_unique_evaluation_campaign_scope")),
    ]
