# Generated by Django 6.0.5 on 2026-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_alter_evaluationcampaign_semester_number'),
        ('branches', '0003_branch_cash_reserve_target'),
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicclass',
            name='unique_academic_class_per_programme_branch_year_level',
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('programme', 'branch', 'academic_year', 'level', 'name'), name='unique_academic_class_per_programme_branch_year_level_name'),
        ),
    ]
