# Generated by Django 6.0.5 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0035_alter_semester_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("NORMAL_ENTRY", "Saisie normale"),
                    ("NORMAL_LOCKED", "Session normale terminee"),
                    ("RETAKE_ENTRY", "Rattrapage"),
                    ("READY_FOR_DIRECTOR", "Transmis au Directeur des etudes"),
                    ("FINALIZED", "Finalise"),
                    ("PUBLISHED", "Publie"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
