# Generated by Django 6.0.1 on 2026-04-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_availabilities', to='branches.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='formations.programme')),
            ],
            options={
                'verbose_name': 'Disponibilité de programme par annexe',
                'verbose_name_plural': 'Disponibilités de programme par annexe',
                'unique_together': {('program', 'branch')},
            },
        ),
    ]
