# Generated by Django 6.0.1 on 2026-04-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_programavailability'),
        ('formations', '0006_programme_updated_at_alter_cycle_theme'),
    ]

    operations = [
    ]
