# Generated by Django 6.0.1 on 2026-04-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_merge_20260417_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramAvailability',
        ),
    ]
