# Generated by Django 6.0.5 on 2026-06-24 10:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_delete_programavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description SEO/reseaux sociaux. Laisser vide pour utiliser la description courte.', max_length=160),
        ),
        migrations.AddField(
            model_name='programme',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre SEO/reseaux sociaux. Laisser vide pour utiliser le titre du programme.', max_length=70),
        ),
        migrations.AddField(
            model_name='programme',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image dediee au partage social (recommande 1200x630px). Laisser vide pour utiliser l'illustration du programme.", null=True, upload_to='programmes/og_images/'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
