# Generated by Django 6.0.5 on 2026-09-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0009_programme_meta_description_programme_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='admissions_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
