# Generated by Django 6.0.5 on 2026-06-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_cycle', '0001_initial'),
        ('academics', '0022_academic_decision_log'),
        ('branches', '0003_branch_cash_reserve_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('normal', 'Normale'), ('retake', 'Rattrapage')], max_length=10)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requested_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('expired', 'Expiree'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grade_modifications', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_modification_requests', to='branches.branch')),
                ('ec_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='academics.ecgrade')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_modification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de correction de note',
                'verbose_name_plural': 'Demandes de correction de note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='academic_cy_branch__c7cd69_idx'), models.Index(fields=['ec_grade', 'status'], name='academic_cy_ec_grad_95fadc_idx')],
            },
        ),
    ]
