# Generated by Django 6.0.5 on 2026-08-31 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_cycle', '0002_grademodificationrequest'),
        ('academics', '0035_alter_semester_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyeardecision',
            name='source_enrollment',
            field=models.ForeignKey(blank=True, help_text='Inscription académique source de la synthèse annuelle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_cycle_decisions', to='academics.academicenrollment'),
        ),
        migrations.AddField(
            model_name='studentyeardecision',
            name='synthesis_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Synthèse calculée des semestres conservée avant la délibération finale.'),
        ),
    ]
