from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("academic_cycle","0003_studentyeardecision_source_enrollment_and_more"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.AddField(model_name="studentyeardecision",name="jury_decision",field=models.CharField(blank=True,choices=[("promoted","Promu"),("promoted_with_academic_debt","Promu avec dette academique"),("repeated","Redouble"),("graduated","Diplome"),("dropped","Abandon"),("transferred","Transfere"),("pending","En attente")],db_index=True,max_length=40)),
        migrations.AddField(model_name="studentyeardecision",name="jury_reason",field=models.CharField(blank=True,max_length=40)),
        migrations.AddField(model_name="studentyeardecision",name="jury_justification",field=models.TextField(blank=True)),
        migrations.AddField(model_name="studentyeardecision",name="jury_processed",field=models.BooleanField(db_index=True,default=False)),
        migrations.AddField(model_name="studentyeardecision",name="jury_decided_at",field=models.DateTimeField(blank=True,null=True)),
        migrations.AddField(model_name="studentyeardecision",name="jury_decided_by",field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="jury_year_decisions",to=settings.AUTH_USER_MODEL)),
        migrations.CreateModel(name="ClassDeliberationSession",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("status",models.CharField(choices=[("preparation","Préparation"),("in_session","En séance"),("ready","Prête à transmettre"),("transmitted","Transmise au DG"),("official","Officielle")],db_index=True,default="preparation",max_length=20)),("normal_threshold",models.DecimalField(blank=True,decimal_places=2,max_digits=5,null=True)),("session_threshold",models.DecimalField(blank=True,decimal_places=2,max_digits=5,null=True)),("session_rule_reason",models.TextField(blank=True)),("opened_at",models.DateTimeField(blank=True,null=True)),("prepared_at",models.DateTimeField(blank=True,null=True)),("transmitted_at",models.DateTimeField(blank=True,null=True)),("transmission_snapshot",models.JSONField(blank=True,default=dict)),("academic_class",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="deliberation_session",to="academics.academicclass")),("academic_year",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="deliberation_sessions",to="academics.academicyear")),("branch",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="deliberation_sessions",to="branches.branch")),("opened_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="opened_deliberation_sessions",to=settings.AUTH_USER_MODEL))],options={"indexes":[models.Index(fields=["branch","academic_year","status"],name="academic_c_branch__c89d88_idx")]})]
